### PR TITLE
IDE-3556 source format on com.liferay.ide.maven.core

### PR DESCRIPTION
**Pull request by Camork**
IDE-3556 source format on com.liferay.ide.maven.core

### CODE REVIEW

**Comment by Camork** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
hey @Camork , please send this pr to SImon and let him to help to sent to Greg after simon finish the review in his side, thanks

**Comment by Camork** [comment]
ok

**Comment by jtydhr88** [comment]
And please make sure there is no test error in your local

**Pull request closed without merging**
