### PR TITLE
Add sdk 62 tests support

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
ci:retest

**Comment by yanan** [comment]
Build Successful.
 237 tests run, 11 skipped, 0 failed.
Test Passed on Jenkins http://ide-build-1:9090/ on this commit 747505ab56aa37c1e605c8dd559d94bf6c3c6b6e on build 74

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/74/checker.html for detailed testing results

**Comment by yanan** [comment]
Test Passed on Jenkins http://ide-build-1:9090/ on this commit 747505ab56aa37c1e605c8dd559d94bf6c3c6b6e on build 74

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/74/checker.html for detailed testing results

**Comment by yanan** [comment]
Build Successful.
 237 tests run, 12 skipped, 0 failed.
Test Passed on Jenkins http://ide-build-1:9090/ on this commit c62bb1f6cf23aafb1413028faa6901679fce43e5 on build 78

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/78/checker.html for detailed testing results

**Comment by yanan** [comment]
Test Passed on Jenkins http://ide-build-1:9090/ on this commit c62bb1f6cf23aafb1413028faa6901679fce43e5 on build 78

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/78/checker.html for detailed testing results

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2820. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
