### PR TITLE
IDE-2015 Failed to create maven project on ide223 on Eclipse Mars

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by gamerson** [comment]
Hey Simon,

Did Ashley check this build and see if it worked?

On Tue, Jul 14, 2015 at 10:07 AM, simon.jiang <notifications@github.com>
wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/gamerson/liferay-ide/pull/1071
> Commit Summary
>
>    - IDE-2015 Failed to create maven project on ide223 on Eclipse Mars
>
> File Changes
>
>    - *M*
>    maven/plugins/com.liferay.ide.maven.core/src/com/liferay/ide/maven/core/LiferayMavenProjectProvider.java
>    <https://github.com/gamerson/liferay-ide/pull/1071/files#diff-0> (12)
>
> Patch Links:
>
>    - https://github.com/gamerson/liferay-ide/pull/1071.patch
>    - https://github.com/gamerson/liferay-ide/pull/1071.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/liferay-ide/pull/1071>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by simonjhy** [comment]
Hi greg, Ashely didn't check it. You mean she need to make temp build  to test this issue?

**Comment by gamerson** [comment]
Yes can you make a temp build for her and send it to her to try to see if
it fixed the issue?

On Tue, Jul 14, 2015 at 11:00 AM, simon.jiang <notifications@github.com>
wrote:

> Hi greg, Ashely didn't check it. You mean she need to make temp build to
> test this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/liferay-ide/pull/1071#issuecomment-121117840>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by yanan** [comment]
I've build an updatesite using Simon's 2.x branch and tested it on eclipse-mars, it works now.

**Comment by gamerson** [comment]
great i'll merge it on 2.x branch and Ashley canyou send a commit to update to version 2.2.4?

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Good deal, we may need one more backport from the sapphire 9 stuff that
Terry is going to do.

On Tue, Jul 14, 2015 at 1:16 PM, Ashley Yuan <notifications@github.com>
wrote:

> I've build an updatesite using Simon's 2.x branch and tested it on
> eclipse-mars, it works now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/liferay-ide/pull/1071#issuecomment-121134682>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Pull request merged**
