### PR TITLE
IDE-4135 New module ext wizard

### PR DESCRIPTION
**Pull request by Camork**

### CODE REVIEW

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
hey @Camork  can you rebase and resend this on type of master?  Thanks!

**Comment by Camork** [comment]
Done

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/3976. [See changes here.](https://github.com/gamerson/liferay-ide/compare/a547a29e1~1...a547a29e1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
