### PR TITLE
include blade.cli.jar in to build

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit e2fb785df86a035be95e96c11ed57d01b43511bf on build 157

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 07ab126c57eb6bdc9d33ad81e4638e2856209aa8 on build 158

**Comment by gamerson** [comment]
Merged, thanks! See 2accf10...07ab126 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 07ab126c57eb6bdc9d33ad81e4638e2856209aa8 on build 157

**Pull request merged**
