### PR TITLE
IDE-1963 check the folder exsit or not

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by gamerson** [comment]
Does this code change allow the project creation to actually work?  don't we need to modify the SDK launch to not use ant but invoke the gradle script instead?

**Comment by jtydhr88** [comment]
We don't need to modify the SDK Launch. Actually it's still using the ant task name "create" and just remove the "portlet.parent.dir" property.it will invoke gradle script by itself.You can see the build.xml in "portlet" folder.But now I think it can't be allow using custom location from this version, and it will to be able to create the project folder in "portlet" folder only, so I change the validation in our Wizard.

**Comment by gamerson** [comment]
i see

**Comment by gamerson** [comment]
Lets change our sdk code to execute a external tools launch for create.sh and not directly invoke ant to run theproject create script.  This should make it support both ant and gradle based project setup scripts.

**Comment by gamerson** [comment]
closing see comments, please resend.

**Pull request closed without merging**
