### PR TITLE
IDE-4654 new liferay spring mvc portlet

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by yanan** [comment]
jenkins retest

**Comment by simonjhy** [comment]
jenkins retest

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
ci:retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
