### PR TITLE
IDE-4710 remove legacy sdk project and old 6.2.x server

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by yanan** [comment]
Source format successfully.

**Comment by yanan** [comment]
Integration Tests Build Failed.

Tests Failed on http://ide-build-1:9090/job/Integration-Tests-Checker//1008

**Comment by yanan** [comment]
Source format successfully.

**Comment by yanan** [comment]
Source format successfully.

**Comment by simonjhy** [comment]
ci:retest

**Comment by yanan** [comment]
Integration Tests Build Failed.

Tests Failed on http://ide-build-1:9090/job/Integration-Tests-Checker//1010

**Comment by yanan** [comment]
Source format successfully.

**Comment by yanan** [comment]
Integration Tests Build Failed.

Tests Failed on http://ide-build-1:9090/job/Integration-Tests-Checker//1013

**Pull request closed without merging**
