### PR TITLE
IDE-4656 improve logic of handling memory args and external properties

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
ft retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/simonjhy/liferay-ide/pull/151. [See changes here.](https://github.com/gamerson/liferay-ide/compare/693655283~5...693655283) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by simonjhy** [comment]
Thanks greg, I will test it today.

**Pull request closed without merging**
