### PR TITLE
IDE-3972 we do not need a strict validation for sdk location

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @jtydhr88  can you share why this needs to be avoided?

**Comment by jtydhr88** [comment]
It will validate the app server configuration is valid(must point to an existing server location), otherwise it throws error.
I don’t think in our planner, we need the legacy sdk has full configuration, we just need the “code” inside in.

**Comment by jtydhr88** [comment]
Even we need one 62server in some cases, we could add one step or action to ask for , instead of a validation to prompt users they need to config it.

**Comment by yanan** [comment]
internet probelm: it retest

**Comment by gamerson** [comment]
@jtydhr88  I agree, we don't need fuill configuration (build.properties) we just need the "SDK layout" is correct.  Can you send an update for this validation?

**Pull request closed without merging**
