### PR TITLE
IDE-2888 Add new MVCPortlet template in New Component wizard

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit dd8839cb8d6825ed749cb6aa98831f3fd8fd1b6b on build 116

**Comment by yanan** [comment]
Hi @gamerson ,

This compile problem has been fixed in Andy's #1823 . And I've merged #1823 and #1825 to your origin master after discussing with the devs to make liferay ide build successfully.

Please help push and check to see if there is anything needs to be updated.

**Comment by gamerson** [comment]
Also can you rebase to the latest master?  Thanks!

**Comment by gamerson** [comment]
Can you rebase to latest master, and add junit tests for this new wizard (not UI tests) thanks.

**Pull request closed without merging**
