### PR TITLE
IDE-3393 make custom composite in ide adapt to Eclipse theme

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by AndyWu2015** [comment]
jenkins retest

**Comment by AndyWu2015** [comment]
jenkins restart

**Comment by AndyWu2015** [comment]
jenkins retest

**Comment by gamerson** [comment]
Merged, thanks! See cead0e2...dd43f82 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
