### PR TITLE
IDE-2006 Liferay Layouttpl project show plugin sdk not set error

### PR DESCRIPTION
**Pull request by aquilabj**

### CODE REVIEW

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Can you rebase this on master?

also can you fix your git name for your commits?


Thanks.

**Comment by aquilabj** [comment]
greg,you mean I need to change my git hub account user name from aquilabj to other name? I have tried this and use change user name in account setting(https://github.com/settings/admin), but it failed to change. I have asked github help about this.

**Comment by gamerson** [comment]
Oh no you need to set it on the command line.

git config --global user.name

On Fri, Jul 3, 2015 at 10:50 AM, simon.jiang <notifications@github.com>
wrote:

> greg,you mean I need to change my git hub account user name from aquilabj
> to other name? I have tried this and use change user name in account
> setting(https://github.com/settings/admin), but it failed to change. I
> have asked github help about this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/liferay-ide/pull/1053#issuecomment-118215375>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Pull request closed without merging**
