### PR TITLE
Remove intellij plugin code

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by gamerson** [comment]
Merged in d9a81eab1d53d703d38803b37e289f8113058d8c <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
