### PR TITLE
IDE-3573 IDE Can't delete project after apply component template

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by yanan** [comment]
Build Successful.
 229 tests run, 11 skipped, 0 failed.
Test Passed on Jenkins http://ide-build-1:9090/ on this commit 56ffa4f4285a13f7c1421c08d8fbe91068f0d7e6 on build 76

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/76/checker.html for detailed testing results

**Comment by yanan** [comment]
Test Passed on Jenkins http://ide-build-1:9090/ on this commit 56ffa4f4285a13f7c1421c08d8fbe91068f0d7e6 on build 76

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/76/checker.html for detailed testing results

**Comment by gamerson** [comment]
thanks @simonjhy 

Hey @jtydhr88  this link isn't working: https://testing-liferayide.wedeploy.io/ui-testing-reports/76/checker.html

**Comment by simonjhy** [comment]
@gamerson , I will check ui test result today, thanks

**Comment by simonjhy** [comment]
@gamerson I checked the content and it seems that final result is ok. The other exception seems no problems.
I found 
INFO] All tests passed!
[JENKINS] Recording test results
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Liferay IDE UI Tests ............................... SUCCESS [  0.371 s]
[INFO] Liferay IDE UI Tools Tests ......................... SUCCESS [  0.017 s]
[INFO] Liferay IDE UI Code Upgrade Tests .................. SUCCESS [01:58 min]
[INFO] Liferay IDE UI Fragment Tests ...................... SUCCESS [22:16 min]
[INFO] Liferay IDE UI Theme Tests ......................... SUCCESS [02:09 min]
[INFO] Liferay IDE UI Hook Tests .......................... SUCCESS [07:50 min]
[INFO] Liferay IDE UI JSF Tests ........................... SUCCESS [03:30 min]
[INFO] Liferay IDE UI Layout Template Tests ............... SUCCESS [05:06 min]
[INFO] Liferay IDE UI Portlet Tests ....................... SUCCESS [06:20 min]
[INFO] Liferay IDE UI Module Tests ........................ SUCCESS [08:50 min]
[INFO] Liferay IDE UI SDK Tests ........................... SUCCESS [05:16 min]
[INFO] Liferay IDE UI Server Tests ........................ SUCCESS [10:16 min]seems that 
[INFO] Liferay IDE UI Workspace Tests ..................... SUCCESS [06:35 min]
[INFO] Liferay IDE UI Service Builder Tests ............... SUCCESS [10:41 min]
[INFO] ------------------------------------------------------------------------

**Pull request merged**
