### PR TITLE
IDE-2959 add theme contributor preference and contributorType property

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by AndyWu2015** [comment]
ci:retest

**Comment by AndyWu2015** [comment]
ci:start

**Comment by AndyWu2015** [comment]
ci:test

**Comment by AndyWu2015** [comment]
jenkins retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/1912. [See changes here.](https://github.com/gamerson/liferay-ide/compare/97a3ad2~2...97a3ad2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
