### PR TITLE
IDE-2663 Code Upgrade Base UI

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
Hey Greg,
This is a very base UI for Code Upgrade.
For your test:
1, create a project and create a file named liferay-code-upgrade.xml
2.double click this file and it will open the editor named Liferay Code Upgrade Tool.

Actually I didn't add any real work on it,there are just some steps and ui demo.
Please let me know it is way is ok or not, thanks.

**Comment by jtydhr88** [comment]
For the real work we can create a hidden project and create a file in it and opened by our editor(Code Upgrade Tool)

**Comment by jtydhr88** [comment]
Now I got some questions for sapphire:
1, how can I disable the outline items we wouldn't like to user click them by their-self.
2, how can I make the two buttons in one row?

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
please resend in project.core/ui, thanks!

**Comment by gamerson** [comment]
Please resend, thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
