### PR TITLE
IDE-4324 register listenerRegistryService

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
internet problem: ft retest

**Comment by yanan** [comment]
internet problem: ft retest

**Comment by yanan** [comment]
ft retest

**Comment by gamerson** [comment]
thanks @Camork !

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
