### PR TITLE
IDE-3884 fix failed to execute maven deploy goal if no generated jar …

### PR DESCRIPTION
**Pull request by jtydhr88**
…in intellij

### CODE REVIEW

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
ci:retest

**Comment by JoyeLuo** [comment]
ci:retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/3150. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
