### PR TITLE
IDE UI test  of Kaleo workflow

### PR DESCRIPTION
**Pull request by haoyisun**
IDE UI test  of Kaleo workflow

### CODE REVIEW

**Comment by yanan** [comment]
Build Failed.
 164 tests run, 11 skipped, 88 failed.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 6cc1794efa2ab0af24bdf0cefb7e03586bc17590 on build 27

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 6cc1794efa2ab0af24bdf0cefb7e03586bc17590 on build 27

**Comment by gamerson** [comment]
hello @haoyisun  can you rebase this on master?  Thanks!

**Comment by haoyisun** [comment]
OK

**Comment by haoyisun** [comment]
hi @gamerson  have pull request to you

**Pull request closed without merging**
