### PR TITLE
update blade to 3.6.0

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
ft retest

**Comment by gamerson** [comment]
hey @yanan  so these errors here: http://cloud-10-50-0-162:8081/job/liferay-ide-pr-tester/2154/#showFailuresLink 

They can't re-produced locally? Does that mean that our tycho surefire plugin is building the wrong features or aren't correctly installing m2e?

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/4308. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
