### PR TITLE
Ui tests

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
jenkins retest

**Comment by gamerson** [comment]
hey @jtydhr88  do you want me to wait until the build passes before I merge?

**Comment by jtydhr88** [comment]
Yes please to wait them passed, I will let them passed by the end of this week.

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
jenkins retest

**Pull request closed without merging**
