### PR TITLE
Update functional tests

### PR DESCRIPTION
**Pull request by yanan**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @simonjhy and @yanan  could yall take a look at the failing tests here: https://github.com/gamerson/liferay-ide/pull/5194/checks?check_run_id=1394893092

is there something we could fix here?

**Comment by gamerson** [comment]
hey @yanan  i see that the functional-tests-pr failed.  is this something that I should go ahead and merge? I wish I could see those tests results. ❓

**Comment by yanan** [comment]
it retest

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
it retest

**Comment by yanan** [comment]
Hi @gamerson , please do not merge. I will check the unstable ones tomorrow and send a new pr once done.

**Pull request closed without merging**
