### PR TITLE
IDE-3554 ui test about kaleo

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
Build Failed.
 No test results found.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 94c5395bf14f651e8066218448d1083704497f8e on build 2

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/2/checker.html for detailed testing results

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 94c5395bf14f651e8066218448d1083704497f8e on build 2

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/2/checker.html for detailed testing results

**Comment by gamerson** [comment]
hey @jtydhr88  can you check out the failing test?

**Comment by jtydhr88** [comment]
hey @gamerson it failed as Ashley and I are still working on re-setting up the tests servers work.

**Comment by yanan** [comment]
Will upload test resources and retest.

**Comment by yanan** [comment]
@gamerson @jtydhr88 
About UI tests:
1. Terry helped set up 2 our existing testing machine to Linux OS
2. UI test failed most because of the internet problem since it's a clean environment about out Linux testing machine
3. As Terry may shared with you, we run every single test project as a Jenkins job , I mean one test project is a Jenkins checker job now, and this will be improved later.
Will share a new doc to explain once done.

**Comment by yanan** [comment]
Build Failed.
 18 tests run, 0 skipped, 18 failed.
Portlet test Failed on Jenkins http://ide-build-1:9090/ on this commit 94c5395bf14f651e8066218448d1083704497f8e on build 2

**Comment by yanan** [comment]
Portlet test Failed on Jenkins http://ide-build-1:9090/ on this commit 94c5395bf14f651e8066218448d1083704497f8e on build 2

**Comment by yanan** [comment]
Build Failed.
 13 tests run, 1 skipped, 12 failed.
Server test Failed on Jenkins http://ide-build-1:9090/ on this commit 94c5395bf14f651e8066218448d1083704497f8e on build 2

**Comment by yanan** [comment]
Server test Failed on Jenkins http://ide-build-1:9090/ on this commit 94c5395bf14f651e8066218448d1083704497f8e on build 2

**Comment by yanan** [comment]
Build Failed.
 No test results found.
Theme test Failed on Jenkins http://ide-build-1:9090/ on this commit 94c5395bf14f651e8066218448d1083704497f8e on build 2

**Comment by yanan** [comment]
Theme test Failed on Jenkins http://ide-build-1:9090/ on this commit 94c5395bf14f651e8066218448d1083704497f8e on build 2

**Comment by yanan** [comment]
Build Failed.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 94c5395bf14f651e8066218448d1083704497f8e on build 7

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
Build Successful.
Test Passed on Jenkins http://ide-build-1:9090/job/Multiple-Job-Test/ on this commit 94c5395bf14f651e8066218448d1083704497f8e on build 18

**Comment by yanan** [comment]
ci:retest

**Pull request closed without merging**
