### PR TITLE
add some csv files to store the 6.1 to 6.2 breaking changes

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
ci:retest

**Comment by jtydhr88** [comment]
net issue

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
ci:retest

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
QA servers lost connection: jenkins retest

**Comment by jtydhr88** [comment]
ci:retest

**Comment by jtydhr88** [comment]
hey Greg,
I am preparing to work on the 6.1 upgrade, those files I analyze to store some breaking changes from 6.1 to 6.2

**Comment by gamerson** [comment]
but these files have `62` in the name?

**Comment by jtydhr88** [comment]
you mean the parent folder name **liferay62**? Now we are using **liferay70** as the folder name to store from 6.2 to 7.0 breaking changes. so I used the liferay62 to store 6.1 to 6.2 changes

**Comment by gamerson** [comment]
Merged in 59fee5eee57f1d5deb2f94b55907b3e9516dc04a <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
