### PR TITLE
IDE-4730 Upgrade 7.1 to 7.2,Find upgrade problems plan info display message error

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by yanan** [comment]
Integration Tests Build Failed.

Tests Failed on http://ide-build-1:9090/job/Integration-Tests-Checker//1062

**Comment by yanan** [comment]
Integration Tests Build Failed.

Tests Failed on http://ide-build-1:9090/job/Integration-Tests-Checker//1064

**Comment by simonjhy** [comment]
ci:retest

**Comment by simonjhy** [comment]
ft retest

**Pull request closed without merging**
