### PR TITLE
IDE-3894 Set default bundle url from pom.xml in maven workspace project

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by jtydhr88** [comment]
ci:retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
ci:retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/3215. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
