### PR TITLE
IDE-3553 source format com.liferay.ide.alloy.ui

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
Build Failed.
 190 tests run, 9 skipped, 35 failed.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 3e3cf972a5b0aee54966bf60deeb82c63990f6a7 on build 14

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 3e3cf972a5b0aee54966bf60deeb82c63990f6a7 on build 14

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
ci:retest

**Comment by yanan** [comment]
jenkins retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2754. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by yanan** [comment]
Build Failed.
 190 tests run, 8 skipped, 8 failed.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 3e3cf972a5b0aee54966bf60deeb82c63990f6a7 on build 19

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 3e3cf972a5b0aee54966bf60deeb82c63990f6a7 on build 19

**Pull request closed without merging**
