### PR TITLE
IDE-2151 and IDE-2192

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/AndyWu2015/liferay-ide/pull/6. [See changes here.](https://github.com/gamerson/liferay-ide/compare/117ca41~9...117ca41) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
@AndyWu2015 please review all of my changes here: https://github.com/gamerson/liferay-ide/compare/117ca41~9...117ca41

make sure you understand my changes, we can do a call if needed, thanks!  we are close with this one... just one more pull hopefully :)

**Comment by AndyWu2015** [comment]
yeah , I try to understand all changes . :)

**Comment by AndyWu2015** [comment]
Have reviewed all changes you made and I can understand them so we don't need a call yet :)

**Comment by gamerson** [comment]
thanks @AndyWu2015

**Pull request closed without merging**
