### PR TITLE
Ui tests

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
Build Failed.
 208 tests run, 14 skipped, 6 failed.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 0fd802e18abc62dd2683da1048edf49275e11374 on build 30

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 0fd802e18abc62dd2683da1048edf49275e11374 on build 30

**Comment by jtydhr88** [comment]
ci:retest

**Comment by yanan** [comment]
Build Failed.
 208 tests run, 14 skipped, 6 failed.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 7bf382d0bbe621bd7bb49191577c7a8ebfeb895e on build 31

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 7bf382d0bbe621bd7bb49191577c7a8ebfeb895e on build 31

**Comment by yanan** [comment]
Build Failed.
 208 tests run, 14 skipped, 6 failed.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit cb2658cbf2d222f5df971dd63efa9f4dc179a0d9 on build 32

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit cb2658cbf2d222f5df971dd63efa9f4dc179a0d9 on build 32

**Comment by jtydhr88** [comment]
@yanan can you take a look at why the ui tests checker doesn't run?

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2769. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
