### PR TITLE
IDE-3594 add projects support files and add test case for validate component

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
ci:retest

**Comment by yanan** [comment]
jenkins retest

**Comment by gamerson** [comment]
Merged in 87ad95b9bbe6e8d373a0ebc84aa4c110ee28d1f2 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
