### PR TITLE
add wedeploy support to store ui tests log file

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
Build Successful.
 218 tests run, 14 skipped, 0 failed.
Test Passed on Jenkins http://ide-build-1:9090/ on this commit e742418cfea854d4a6c23e429f98a1fb3f4c1f4d on build 54

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/54/checker.log for detailed testing results

**Comment by yanan** [comment]
Test Passed on Jenkins http://ide-build-1:9090/ on this commit e742418cfea854d4a6c23e429f98a1fb3f4c1f4d on build 54

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/54/checker.log for detailed testing results

**Comment by gamerson** [comment]
hey @jtydhr88  this code is specific to the infrastructure we have in China office, so I think it should go under a different repository.  It could be the same repository that you use to upload the items to wedeploy.

**Comment by jtydhr88** [comment]
ok, I will move these codes to another repo

**Pull request closed without merging**
