### PR TITLE
Add blade jar

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
By this fix, we can create module projects.

**Comment by gamerson** [comment]
Hey Ashley. Can you do another rebuild after I merge this one ?

On Tuesday, February 2, 2016, Ashley Yuan <notifications@github.com> wrote:

> By this fix, we can create module projects.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/liferay-ide/pull/1360#issuecomment-178496313>
> .
>


-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged, thanks! See ee5e1ee...da41b36
ee5e1ee...da41b36 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by yanan** [comment]
Sure, I'll do a new RC build.

**Pull request merged**
