### PR TITLE
IDE-3492 null check

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
ci:retest

**Comment by yanan** [comment]
Build Failed.
 237 tests run, 12 skipped, 1 failed.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 6094f49b8d53c659bfce7c16d6192ff5d9662aa8 on build 81

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/81/checker.html for detailed testing results

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 6094f49b8d53c659bfce7c16d6192ff5d9662aa8 on build 81

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/81/checker.html for detailed testing results

**Comment by gamerson** [comment]
@jtydhr88  test failed can you investigate?

**Pull request closed without merging**
