### PR TITLE
Sf check

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
hey @gamerson 
I reverted the sf tool to 1.0.793 as there are many sf checker will be lost, see this 
屏幕快照 2019-04-08 下午5 04 53
it has the obvious sf issues but it still could be passed from 1.0794
I am not sure this is expected behaviors or not.

**Comment by jtydhr88** [comment]
cc @hhuijser

**Comment by gamerson** [comment]
hey @jtydhr88  i can merge this, but can you create a pull and demostrate the problem to Hugo so he can try to get a fix?  I don't want to be stuck on this version.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
