### PR TITLE
Ide 3972

### PR DESCRIPTION
**Pull request by yanan**

### CODE REVIEW

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
it retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/4067. [See changes here.](https://github.com/gamerson/liferay-ide/compare/fa311e79c~6...fa311e79c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
