### PR TITLE
IDE-3560 sf on com.liferay.ide.server.tomcat.core

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by JoyeLuo** [comment]
jenkins:retest

**Comment by yanan** [comment]
Internet problem:
jenkins retest

**Comment by jtydhr88** [comment]
hey @yanan we need to retest the automatic if we catch the error caused by internet issue

**Comment by gamerson** [comment]
Merged in 32d3b6935386a8177ff8306f31d431175c886a69 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
