### PR TITLE
UI test case about kaleo

### PR DESCRIPTION
**Pull request by haoyisun**
UI test case about kaleo

### CODE REVIEW

**Comment by yanan** [comment]
Build Failed.
 224 tests run, 14 skipped, 1 failed.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit b5ec72d408d3477c4c8852338b09ffb571af97a5 on build 48

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit b5ec72d408d3477c4c8852338b09ffb571af97a5 on build 48

**Comment by jtydhr88** [comment]
@haoyisun please check why the tests failed, thanks

**Comment by haoyisun** [comment]
ok

**Pull request closed without merging**
