### PR TITLE
IDE-2958 move this test to maven plugin since it requires maven plugins

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 864fd506841fa5043f9e6e5a42e4f7dbfc582383 on build 167

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit c1f91352c665736927ee529876ffce9418874df7 on build 168

**Comment by gamerson** [comment]
Merged, thanks! See 85e3335...7e42bd3 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit e15fa332859c15e043940ab031876cca8f46c773 on build 169

**Comment by yanan** [comment]
Test Passed on Jenkins http://ide-build-1:9090/ on this commit 273b9d8d4ba1c019a7d814383d51072ce9ab125c on build 172

**Comment by yanan** [comment]
Test Passed on Jenkins http://ide-build-1:9090/ on this commit be70f4cced039cecd1ac9f34647dee9bf344e1bd on build 173

**Comment by yanan** [comment]
Test Passed on Jenkins http://ide-build-1:9090/ on this commit 4f2bbf69993c7a7e44634509802312b684e1afd2 on build 174

**Pull request closed without merging**
