### PR TITLE
IDE-4648 use custom PortletDefinitionRootElementController to support portlet xls in different namespace and version

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
@jtydhr88  Now that we have this merged, we can add the portlet 3.0 specific properties on the model.

**Comment by gamerson** [comment]
hey @yanan  can you check these failures?  are they related to the portlet.xml editors?

**Comment by jtydhr88** [comment]
it retest

**Comment by jtydhr88** [comment]
ft retest

**Comment by yanan** [comment]
Hey @gamerson and @jtydhr88 , the error is not related to portlet.xml. The failure is about npm validation message changed in https://github.com/gamerson/liferay-ide/pull/4647, while the functional tests has not been updated yet.

**Comment by yanan** [comment]
integration tests is because of the internet: it retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged in 960e6c2126f1c13a640679911a219f6a071d8bad. Thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
