### PR TITLE
IDE-3598 Code Upgrade PropertiesFileChecker didn't close inputStream

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
sent to Greg, thanks.

**Comment by yanan** [comment]
Build Failed.
 No test results found.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 949a0976913a54895ca86f11ff5ae49c0c2fd358 on build 3

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/3/checker.html for detailed testing results

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 949a0976913a54895ca86f11ff5ae49c0c2fd358 on build 3

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/3/checker.html for detailed testing results

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2844. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
