### PR TITLE
IDE-4139 add suport for breaking changne version

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
re-configure new added kaleo tests, ft retest

**Comment by yanan** [comment]
Lable 'Plugins SDK or Maven Project Root Location' updated in this commit. 
ft retest

**Comment by yanan** [comment]
ft retest

**Comment by gamerson** [comment]
Closed see email.  Please rebase and resend.  Thanks!

**Pull request closed without merging**
