### PR TITLE
IDE-4450 update bundle support and ce portal in installer

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
it retest

**Comment by jtydhr88** [comment]
ci:retest

**Comment by jtydhr88** [comment]
ft retest

**Comment by yanan** [comment]
ft retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/3871. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
