### PR TITLE
IDE-3599 check service name's validity before finish

### PR DESCRIPTION
**Pull request by jtydhr88**
Just give a warning in case another situation

### CODE REVIEW

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
ci:retest

**Comment by gamerson** [comment]
There may be services that are valid but we didn't find them, so I dont' think we should limit the to only what we can find as valid service.

**Comment by Camork** [comment]
Got it.

**Pull request closed without merging**
