### PR TITLE
IDE-4654 new liferay spring mvc portlet

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by yanan** [comment]
Integration Tests run successfully.

**Comment by yanan** [comment]
ci:retest

**Comment by yanan** [comment]
Integration Tests run successfully.

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
Integration Tests run successfully.

**Comment by yanan** [comment]
ft retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/4809. [See changes here.](https://github.com/gamerson/liferay-ide/compare/beb611842~13...beb611842) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
