### PR TITLE
IDE-2886 add a Liferay 7 Code Upgrade View with animated gears

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
Test Passed on Jenkins http://ide-build-1:9090/ on this commit 0409afaa4e5b7b0da41b0a6bfd66481860934e18

**Comment by AndyWu2015** [comment]
here is the sample sdk-project https://drive.google.com/a/liferay.com/file/d/0B7MdbsiSkzERV3ZMalhqR0p3cGs/view?usp=sharing

**Comment by yanan** [comment]
Test Passed on Jenkins http://ide-build-1:9090/ on this commit 25c8698a7c47e4650ad016f7d95e1b3c1d84f5b0 on build 21

**Comment by gamerson** [comment]
I've merged this onto a branch here: https://github.com/gamerson/liferay-ide/tree/Code_Upgrade
 we can work from this branch until we are ready to move to master

**Pull request closed without merging**
