### PR TITLE
detect wars under lr-ws according configuration

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit fe925a44c6c1f5d1ae782393bc66b1cd5fb3e64d on build 192

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 0339d32e017f01c47d25407b5c50722369ba1377 on build 194

**Comment by yanan** [comment]
Test Passed on Jenkins http://ide-build-1:9090/ on this commit f6b8eca951eb1d49266d65f1595589e8901b70d0 on build 195

**Comment by gamerson** [comment]
Merged, thanks! See 497dcfb...df07442 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
