### PR TITLE
IDE-2999 fix merging parameters with space

### PR DESCRIPTION
**Pull request by AndyWu2015**
hey Greg , the PortalServerBehavior.mergeArguments method only support there style arguments , 
1. -a bc (bc can include space)
2. a=b (b can include space)
3. abc (abc can include space)

and jobss  arguments has such style : -abc (abs incudes space)(eg. -Xbootclasspath/p:"D:/dev java/test") and this method can't handle , (be recognized as:  
-Xbootclasspath/p:"D:/dev 
java/test" )
so I just deal such parameter specially , when merging i ignore all such parameters , and after merging , I just remove all existing ones ,and append new ones.

So in this way , if user add new Xbootclasspath , it will be ignored. is this ok ? or should I need to check if new classpath addded ?

### CODE REVIEW

**Comment by gamerson** [comment]
Merged, thanks! See 293b9b3...769767b <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
@yanan  can you test this pull with the following tests?

1. setup both tomcat and jboss servers with spaces in the path
2. start both servers with default args
3.  add custom launch args in both of these in both the portal server editor and in the launch config screen
4. verify that the launches still work and also that we can 'restore defaults' back to original

**Comment by gamerson** [comment]
@yanan i've merged this already but I just want to make sure it works with wider testing.

**Comment by yanan** [comment]
@gamerson 

Changing args in server editor works.
Changing args in launch config works with clicking on 'Run' button in launch configurations page. But sometimes we will run into an error about server is always 'Starting'(IDE-3050).

https://issues.liferay.com/browse/IDE-3050

**Pull request closed without merging**
