### PR TITLE
IDE-4585 Add support for new liferay service builder on module project

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
it retest

**Comment by jtydhr88** [comment]
ci:retest

**Comment by jtydhr88** [comment]
ft retest

**Comment by jtydhr88** [comment]
ft retest

**Comment by jtydhr88** [comment]
ft retest

**Comment by jtydhr88** [comment]
LIFERAY_UPGRADE_PLANNER_ACTIONS

**Comment by yanan** [comment]
We won't add support for this type of feature.

**Pull request closed without merging**
