### PR TITLE
IDE-2769 add deploy module gradle test according to the bundle type

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
hey @yanan lets add test per test class file, after we fix unstable problem, we will add the rest of tests back.

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/3170. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
