### PR TITLE
IDE-2760 update validate module project test and maven workspace test…

### PR DESCRIPTION
**Pull request by yanan**
… files

### CODE REVIEW

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
ci:retest

**Comment by yanan** [comment]
ci:retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2661. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
