### PR TITLE
add liferay version 71 checker and make sure only higher version checker running if the title is same

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
Java problem. it retest

**Comment by jtydhr88** [comment]
ft retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/jtydhr88/liferay-ide/pull/683. [See changes here.](https://github.com/gamerson/liferay-ide/compare/eea577d02~2...eea577d02) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/3579. [See changes here.](https://github.com/gamerson/liferay-ide/compare/a29b27630~2...a29b27630) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
