### PR TITLE
remote agent jar from static and add or update agent into modules

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by AndyWu2015** [comment]
jenkins retest

**Comment by AndyWu2015** [comment]
jenkins retest

**Comment by AndyWu2015** [comment]
no test fail , just timeout

**Comment by gamerson** [comment]
Merged, thanks! See 5e7673c...08f36f7 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
