### PR TITLE
IDE-3972 calculate the enable by action status of higher tasks

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
hey @gamerson , even I implemented it in backend, but by reading the following talks about TreeItem, it seems that we could not easily disable the TreeItem.
How do you think of that?

**Comment by jtydhr88** [comment]
see more here:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=145628
https://www.eclipse.org/forums/index.php/t/103773/

**Comment by gamerson** [comment]
> hey @gamerson , even I implemented it in backend, but by reading the following talks about TreeItem, it seems that we could not easily disable the TreeItem.
> How do you think of that?

Hey Terry, no problem we can use other 'font' or 'coloring' that will make it look disabled (grayscaled or lighter)

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/4022. [See changes here.](https://github.com/gamerson/liferay-ide/compare/8da48e6c7~3...8da48e6c7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
