### PR TITLE
fix maven tests

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
jenkins retest

**Comment by AndyWu2015** [comment]
jenkins retest

**Comment by AndyWu2015** [comment]
jenkins retest

**Comment by AndyWu2015** [comment]
I can run the junit tests successfully.

**Comment by gamerson** [comment]
jenkins retest

**Comment by gamerson** [comment]
jenkins retest

**Comment by gamerson** [comment]
jenkins retest

**Comment by gamerson** [comment]
Merged, thanks! See a468112...004f196 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
