### PR TITLE
modify kaleo ui test

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
hey @gamerson the ui tests already passed on the china server but the status doesn't update

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by gamerson** [comment]
thanks @jtydhr88 @haoyisun

**Pull request merged**
