### PR TITLE
sf on ide.ui

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
ft retest

**Comment by jtydhr88** [comment]
ft retest

**Comment by jtydhr88** [comment]
it retest

**Comment by jtydhr88** [comment]
ci:retest

**Comment by jtydhr88** [comment]
ft retest

**Comment by gamerson** [comment]
Merged in c7ed2519641b4f8689636dd20079952ba94377a9. Thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
