### PR TITLE
fix Component Class Name label

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by yanan** [comment]
Liferay ide build succesfully with this commit.

**Comment by AndyWu2015** [comment]
thanks @yanan  it doesn't matter

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged, thanks! See 871cd59...56665a0 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
