### PR TITLE
IDE UI test  of Kaleo workflow

### PR DESCRIPTION
**Pull request by jtydhr88**
thanks @haoyisun worked on kaleo ui tests

### CODE REVIEW

**Comment by yanan** [comment]
Can one of the admins verify this patch?

**Comment by yanan** [comment]
Build Successful.
 No test results found.
Test Passed on Jenkins http://ide-build-1:9090/ on this commit 912d8e6bde26fdafdabb81c17c60dcca62569c90 on build 4

**Comment by yanan** [comment]
Test Passed on Jenkins http://ide-build-1:9090/ on this commit 912d8e6bde26fdafdabb81c17c60dcca62569c90 on build 4

**Comment by yanan** [comment]
ok to test

**Comment by yanan** [comment]
Sorry, testing for ui-tests pull request tester on build-1.

**Comment by yanan** [comment]
Build Failed.
 No test results found.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 912d8e6bde26fdafdabb81c17c60dcca62569c90 on build 6

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 912d8e6bde26fdafdabb81c17c60dcca62569c90 on build 6

**Comment by yanan** [comment]
Build Failed.
 No test results found.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 912d8e6bde26fdafdabb81c17c60dcca62569c90 on build 9

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 912d8e6bde26fdafdabb81c17c60dcca62569c90 on build 9

**Comment by gamerson** [comment]
hey @haoyisun  can you rebase and resend?  thanks!

**Comment by haoyisun** [comment]
ok,got it

**Pull request closed without merging**
