### PR TITLE
remove old code upgrade tool

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
ft retest

**Comment by gamerson** [comment]
hey @jtydhr88   what about the functional tests... is the failure related?

**Comment by jtydhr88** [comment]
hey @gamerson the functional tests failed on the Module ext and target platform(index.sources), we need to fix tests to adapt the latest target platform changes.

**Comment by gamerson** [comment]
Thanks for update. I"ll merge this then.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/4496. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
