### PR TITLE
IDE-3581 Maven circularly deploy project

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by yanan** [comment]
Build Failed.
 207 tests run, 13 skipped, 8 failed.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 6e7288f55fa22d15db5205ef4749af7941a860e5 on build 25

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 6e7288f55fa22d15db5205ef4749af7941a860e5 on build 25

**Comment by jtydhr88** [comment]
hey @simonjhy I am not sure Greg will agree with your solution, I think we need more talk about it

**Comment by jtydhr88** [comment]
need more research

**Pull request closed without merging**
