### PR TITLE
Ide 4401

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
Internet Problem: ft retest

**Comment by yanan** [comment]
ft  retest

**Comment by yanan** [comment]
Need to make sure with dev:
when import a Liferay Workspace with Plugins Sdk, the server won't be set up as before.

**Comment by gamerson** [comment]
hey @jtydhr88  @simonjhy  can you look at the test failures on the Jenkins-linux tests?  Those are both maven workspace related test failures so those should be fixed by this pull. 

Also can you take a look at the question that @yanan  asked in her comment?  That should likely be addressed as a part of this as well.

**Comment by simonjhy** [comment]
Hi greg, this is another issue about the liferay gradle workspace import job and add server portal runtime execute sequence problem. I will fix it in this pull

**Pull request closed without merging**
