### PR TITLE
IDE-2273 add '-m2' suffix

### PR DESCRIPTION
**Pull request by yanan**

### CODE REVIEW

**Comment by yanan** [comment]
I've create a tag on my liferay-ide repo, but I found it doesn't work when I send through this pr. Maybe you can help add a tag for 3.0.0.201602031411-m1 at the following commit:

Update blade cli for template fix: https://github.com/gamerson/liferay-blade-tools/pull/113

**Comment by gamerson** [comment]
hey @yanan  i have added a tag here:
https://github.com/liferay/liferay-ide/releases

See there already is a tag for 3.0.0.201602031411-m1  can you see that one?

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged, thanks! See 901e476...d8858c3
901e476...d8858c3 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by yanan** [comment]
Yes, I saw it. Thanks.

**Pull request closed without merging**
