### PR TITLE
show upgrade planner

### PR DESCRIPTION
**Pull request by yanan**

### CODE REVIEW

**Comment by yanan** [comment]
@gamerson and @jtydhr88 
Running our Studio Installer with this commit, upgrade planner perspective shows up, but we do miss most of the icons, please help take a look this afternoon
upgradeplanner

**Comment by jtydhr88** [comment]
hey @yanan do not worry, fix in there https://github.com/gamerson/liferay-ide/pull/4105

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/4106. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
hey @yanan  and @jtydhr88  can you investigate these failures? 
http://cloud-10-50-0-162:8081/job/liferay-ide-pr-tester/1984/

**Pull request closed without merging**
