### PR TITLE
Ide 3972

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
internet problem, ft retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/3997. [See changes here.](https://github.com/gamerson/liferay-ide/compare/6c09179f9~1...6c09179f9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
