### PR TITLE
Update Liferay IDE to use the latest blade

### PR DESCRIPTION
**Pull request by christopherbryanboyd**

### CODE REVIEW

**Comment by yanan** [comment]
it retest

**Comment by yanan** [comment]
it retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/4481. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
