### PR TITLE
IDE-4617 make hook wizard adapt to gradle war-hook project

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
internet problem: sf retest

**Comment by yanan** [comment]
sf retest

**Comment by yanan** [comment]
sf retest

**Comment by yanan** [comment]
sf retest

**Comment by yanan** [comment]
it retest

**Comment by yanan** [comment]
it retest

**Comment by jtydhr88** [comment]
ft retest

**Comment by jtydhr88** [comment]
ft retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/4692. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
