### PR TITLE
IDE-4692 rename project sdk installer to workspace installer

### PR DESCRIPTION
**Pull request by yanan**
The installers look like the following with this commit:

1. Workspace installer:
    LiferayWorkspace-201910250641-linux-x64-installer.run
2. Workspace with Studio CE installer:
    LiferayWorkspacewithDevStudioCommunityEdition-201910250641-osx-installer.dmg
3. Worksapce with Studio DXP installer:
    LiferayWorkspacewithDevStudioDXP-201910250641-windows-installer.exe

screenshot

### CODE REVIEW

**Comment by yanan** [comment]
THEME_WIZARD_CREATE: ft retest

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
ft retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged in de5ea004baaf1032c29aeb947eedfdf85b63fdc0. Thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
