### PR TITLE
IDE-3594 add error log feature for ui tests

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
it retest

**Comment by yanan** [comment]
ci:retest

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
ft retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged in f18e45928438f5c4d1351e38f7325a8b5ea38225. Thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
