### PR TITLE
IDE-3022 revert isBundleOnlyProject and support projects under lr-ws/…

### PR DESCRIPTION
**Pull request by AndyWu2015**
…wars

### CODE REVIEW

**Comment by AndyWu2015** [comment]
hey Greg , you can go to https://issues.liferay.com/browse/IDE-3022 to see detail of the bug 
And I think it would be better if it is mereged before 3.1 m1

**Comment by yanan** [comment]
jenkins:retest

**Comment by yanan** [comment]
jenkins retest

**Comment by gamerson** [comment]
Hey @AndyWu2015 can you send unit tests for this new change? thanks!

**Pull request closed without merging**
