### PR TITLE
Ide 3967

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by JoyeLuo** [comment]
jenkins:retest

**Comment by JoyeLuo** [comment]
jenkins retest

**Comment by JoyeLuo** [comment]
jenkins retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/3231. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
