### PR TITLE
IDE-2290 revert to buildship api

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jtydhr88** [comment]
Hey Greg, as gradleDelegete never create Processes I revert to the way before and I will find another way for IDE-2262

**Comment by gamerson** [comment]
Ok, yeah we need to find a way to get it to avoid saving those configurations that are just temporary.  Maybe we need a new API.

**Comment by gamerson** [comment]
Merged, thanks! See 687b1dc...3c32cbd
687b1dc...3c32cbd <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
@jtydhr88 try to look at this class RunGradleBuildLaunchRequestJob

**Comment by gamerson** [comment]
maybe there is a way to run a build request without a launch?

**Pull request merged**
