### PR TITLE
IDE-3231 change liferay 6.2 server name and description

### PR DESCRIPTION
**Pull request by JoyeLuo**

### CODE REVIEW

**Comment by JoyeLuo** [comment]
jenkins retest

**Comment by JoyeLuo** [comment]
jenkins retest

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit e18c274fb833e71be8327af838c052ba6de13c7f on build 232

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit e18c274fb833e71be8327af838c052ba6de13c7f on build 235

**Comment by gamerson** [comment]
Merged, thanks! See 7dac96a...e18c274 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
