### PR TITLE
IDE-3553 com.liferay.ide.layouttpl.ui

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit b21dc7d262ce3dffd8c0728758f006a49a103986 on build 13

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2752. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
