### PR TITLE
IDE-2240 install features/plguins to the right place on mac

### PR DESCRIPTION
**Pull request by yanan**

### CODE REVIEW

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged, thanks! See dbd10f6...6c838ab
dbd10f6...6c838ab <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by yanan** [comment]
By the way, after this fix, it still have authorization verify problem on Mac.

**Comment by gamerson** [comment]
Yeah unless we let Apple Sign the app using their signing service (app
store) i don't think there is a way to avoid that problem

On Wed, Feb 17, 2016 at 7:11 PM, Ashley Yuan <notifications@github.com>
wrote:

> By the way, after this fix, it still have authorization verify problem on
> Mac.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/liferay-ide/pull/1372#issuecomment-185491833>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Pull request merged**
