### PR TITLE
Backport

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
Hi Greg,it would be failed when building if you set sapphire as 8.2.
I think because we made the .../sapphire/8.1/... in /build/parent/pom.xml
so I changed the version to 8.1

**Comment by gamerson** [comment]
Thanks Terry for the update.

**Comment by gamerson** [comment]
One thing we need to check.... @yanan can you install a 2.2.4 with this build on Mars and then upgrade try to upgrade to a build of IDE 3.0M1 just to make sure we can upgrade from Sapphire 8.1 to 8.2 without problems.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by yanan** [comment]
Tested.
No errors when upgrade Sapphire 8.1 on ide2.2.4 to Sapphire 8.2 on latest ide3.0.

**Pull request merged**
