### PR TITLE
IDE-3453 update blade cli and change maker type to warning when deprecated version is 7.0

### PR DESCRIPTION
**Pull request by JoyeLuo**

### CODE REVIEW

**Comment by JoyeLuo** [comment]
jenkins retest

**Comment by gamerson** [comment]
thanks @JoyeLuo

**Comment by gamerson** [comment]
i'll merge it today

**Comment by gamerson** [comment]
Merged, thanks! See 468dec3...f963536 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
