### PR TITLE
update com.liferay.blade.cli.jar

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by yanan** [comment]
@gamerson Are we going to merge this into 300M1?

**Comment by yanan** [comment]
By this fix, we can create serviceWrapper module project successfully.

**Comment by gamerson** [comment]
@yanan yes

**Comment by gamerson** [comment]
@yanan can you create teh JIRA ticket?

**Comment by gamerson** [comment]
@AndyWu2015 @yanan i'll include the new CLI once the job finishes.

**Comment by yanan** [comment]
@gamerson I've assigned IDE-2237 to you.

**Pull request closed without merging**
