### PR TITLE
IDE-2590 change the blade repo url to 1.x

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by yanan** [comment]
There are three unit test errors in BladeCLITests:

1. bladeCLIProjectTemplates
2. bladeCLICreateProject
3. bladeCLIExecute

After make sure with Andy, we will get rid of these once the 1.x link exists.

**Comment by gamerson** [comment]
The URL has been updated http://releases.liferay.com/tools/blade-cli/1.x/
so I can merge this now

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged, thanks! See 56665a0...e62830a <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
