### PR TITLE
add code upgrade tests back

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by yanan** [comment]
Build Failed.
 199 tests run, 11 skipped, 18 failed.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 7170fddecf60a5b9b9bfa78ffd4485a60285d269 on build 18

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 7170fddecf60a5b9b9bfa78ffd4485a60285d269 on build 18

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2755. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
