### PR TITLE
let out code depend on CommandProcessor.COMMAND_FUNCTION

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by gamerson** [comment]
@AndyWu2015 hey andy does this dependency exist in our runtime ?  does gogo.runtime get shipped with Eclipse JavaEE by default?

**Comment by AndyWu2015** [comment]
Yes , It is

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged, thanks! See 1f69cc5...e65c849
1f69cc5...e65c849 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
