### PR TITLE
IDE-4264 add the new watch nodes under server

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
Internet Problem: it retest

**Comment by yanan** [comment]
internet problem: sf retest

**Comment by jtydhr88** [comment]
ft retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/3634. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
