### PR TITLE
IDE-4324 Buildship upgrade to 3.x latest

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
Compilation failure on gradle.core integration tests:

> GradleProjectTests.java:[21]
> [ERROR] import com.liferay.ide.gradle.core.GradleCore;

**Comment by simonjhy** [comment]
jenkins retest

**Comment by simonjhy** [comment]
jenkins retest

**Comment by simonjhy** [comment]
ci:retest

**Pull request closed without merging**
