### PR TITLE
IDE-3493 bug fix

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
ci:retest

**Comment by jtydhr88** [comment]
ci:retest

**Comment by yanan** [comment]
Build Failed.
 237 tests run, 12 skipped, 1 failed.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit b621d153b6ce7d586cf551603d8654aa20d4deda on build 80

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/80/checker.html for detailed testing results

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit b621d153b6ce7d586cf551603d8654aa20d4deda on build 80

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/80/checker.html for detailed testing results

**Pull request closed without merging**
