### PR TITLE
IDE-2958 move this test to maven plugin since it requires maven plugins

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
jenkins retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/1864. [See changes here.](https://github.com/gamerson/liferay-ide/compare/864fd50~1...864fd50) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 174ccbb0f75e837c8c12b192c54d50f6ac1c1bb5 on build 165

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 174ccbb0f75e837c8c12b192c54d50f6ac1c1bb5 on build 166

**Comment by gamerson** [comment]
Merged, thanks! See <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
