### PR TITLE
IDE-3338 update bundle url to liferay ga4

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
jenkins retest

**Comment by gamerson** [comment]
jenkins retest

**Comment by JoyeLuo** [comment]
Will resend this pull request for HostOsgiBundle( "com.liferay.asset.display.web-1.0.2.jar" ) version change in ga4.

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2365. [See changes here.](https://github.com/gamerson/liferay-ide/compare/f9dcf50~1...f9dcf50) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
