### PR TITLE
IDE-2973 fix the lack of page problem and make the optimize checkbox

### PR DESCRIPTION
**Pull request by JoyeLuo**
invisible when not choose workspace

### CODE REVIEW

**Comment by yanan** [comment]
Test Passed on Jenkins http://ide-build-1:9090/ on this commit a18d22fa84b366715781c91e427fa215dfd3536c on build 190

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by yanan** [comment]
Test Passed on Jenkins http://ide-build-1:9090/ on this commit a18d22fa84b366715781c91e427fa215dfd3536c on build 191

**Comment by yanan** [comment]
Test Passed on Jenkins http://ide-build-1:9090/ on this commit 828256dbb317c722fa5a92f803948cdcaf3b6347 on build 197

**Comment by gamerson** [comment]
Merged, thanks! See ea2848b...8173792 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
