### PR TITLE
update Swtbotbase and add jacoco config

### PR DESCRIPTION
**Pull request by yanan**

### CODE REVIEW

**Comment by gamerson** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by yanan** [comment]
jenkins retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2584. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
