### PR TITLE
Ide 3340

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
Build Failed.
Test Failed on Jenkins http://ide-build-1:9090/job/Multiple-Job-Test/ on this commit d76151f924e72ca9c943176d4063a3b6b02e668e on build 20

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
Build Failed.
Test Failed on Jenkins http://ide-build-1:9090/job/Multiple-Job-Test/ on this commit d76151f924e72ca9c943176d4063a3b6b02e668e on build 29

**Comment by yanan** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
close to wait ui tests finish and need to rebase on ui tests

**Pull request closed without merging**
