### PR TITLE
IDE-4302 update tests to run more stable

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
fr retest

**Comment by yanan** [comment]
ft retest

**Comment by gamerson** [comment]
ft retest

**Comment by jtydhr88** [comment]
ft retest

**Comment by jtydhr88** [comment]
ft retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
