### PR TITLE
IDE-3038 make a new JSF project wizard for DXP

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 8af59b01b26118136b6684cde94c8fd18cb1eaba on build 211

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 8af59b01b26118136b6684cde94c8fd18cb1eaba on build 212

**Comment by simonjhy** [comment]
jenkins retest

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 8af59b01b26118136b6684cde94c8fd18cb1eaba on build 213

**Comment by yanan** [comment]
jenkikns retest

**Comment by gamerson** [comment]
hey @simonjhy can you rebase?

**Comment by gamerson** [comment]
and resend.

**Comment by simonjhy** [comment]
ok I will after I fix the junit test issue while it run with maven.

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 4b2c32cfc2defb829adc24073d308d6c9dd9c158 on build 221

**Pull request closed without merging**
