### PR TITLE
IDE-3840 fix didn't show bundles folder when create a maven workspace…

### PR DESCRIPTION
**Pull request by jtydhr88**
… with initBundle

### CODE REVIEW

**Comment by JoyeLuo** [comment]
jenkins:retest

**Comment by JoyeLuo** [comment]
jenkins:retest

**Comment by JoyeLuo** [comment]
jenkins:retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/3067. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
