### PR TITLE
IDE-2857 can't lookup auto login

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
jenkins retest

**Comment by simonjhy** [comment]
jenkins retest

**Comment by simonjhy** [comment]
jenkins retest

**Comment by simonjhy** [comment]
jenkins retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2631. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2665. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
