### PR TITLE
IDE-4656 make custom memory args override the original one

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
it:retest

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
it retest

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
it retest

**Comment by yanan** [comment]
ft retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged in 5d3ba98131724fc88026cff151bc3fa1dffca87f. Thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
