### PR TITLE
IDE-3021 detect if it is gradle project

### PR DESCRIPTION
**Pull request by AndyWu2015**
feel free to merge it

### CODE REVIEW

**Comment by gamerson** [comment]
We can wait until M2

**Comment by AndyWu2015** [comment]
okay , it would be better.

**Comment by AndyWu2015** [comment]
jenkins retest

**Comment by gamerson** [comment]
Merged, thanks! See d9bc1d3...fb6b761 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
