### PR TITLE
IDE-4476 fix issue for gradle build service project while execut watch

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by yanan** [comment]
Hello @simonjhy cc @gamerson,

With this commit, there is an integration test error, details are as following:

1. import gradle project  which the following build.gradle:

> buildscript {
>     dependencies {
> 		classpath 'biz.aQute.bnd:biz.aQute.bnd.gradle:3.0.0'
> 		classpath 'com.liferay:com.liferay.ant.bnd:2.0.0'
>     }
> }
> apply plugin: 'biz.aQute.bnd.builder'
> 
2. then after project imported, there is no liferay nature. Is this expected?

**Comment by yanan** [comment]
Error occurs during manual test on Mac: no liferay and gradle natures on liferay gradle JSF project.

Test steps:
1. new LIferay JSF project > choose "Gradle" as build type > finish
2. Add and Remove or drag and drop to server

Error stack:

> An internal error occurred during: "Liferay refresh gradle project job".
> java.util.NoSuchElementException: No value present
> at java.util.Optional.get(Optional.java:135)
> at com.liferay.ide.gradle.core.GradleUtil$1.run(**GradleUtil.java:141**)

Please help update @simonjhy , thanks.

**Comment by simonjhy** [comment]
@yanan I fixed these two issues.  they should be ok now.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/3920. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
