### PR TITLE
IDE-3992

### PR DESCRIPTION
**Pull request by Camork**

### CODE REVIEW

**Comment by Camork** [comment]
jenkins retest

**Comment by Camork** [comment]
jenkins retest

**Comment by Camork** [comment]
jenkins retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/Camork/liferay-ide/pull/4. [See changes here.](https://github.com/gamerson/liferay-ide/compare/e2abab051~1...e2abab051) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
