### PR TITLE
IDE-3340 Liferay IDE check server status error for Liferay Portal CE GA4 for JBoss EAP

### PR DESCRIPTION
**Pull request by jtydhr88**
hey @simonjhy can you try to write some beginning of ui tests for the JBoss server? No need too much detail but just beginning is ok.

### CODE REVIEW

**Comment by jtydhr88** [comment]
you can refer to the tomcat tests and no need to test the server start and deployment right now, I will add them back after I finish the console checker in ui tests

**Comment by simonjhy** [comment]
OK

**Comment by yanan** [comment]
Build Failed.
 No test results found.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit d3bce5786dcc5f61d39d0c774139978fbb3cd46c on build 37

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit d3bce5786dcc5f61d39d0c774139978fbb3cd46c on build 37

**Pull request closed without merging**
