### PR TITLE
update gradle.model and gradle.plugin jar file

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @AndyWu2015 did you send me a pull request on the liferay-blade-cli for the change to the mode and plugin files?

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged, thanks! See d148a6f...1fa5347 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by AndyWu2015** [comment]
No, I thought you can merge it from your side. And now it is merged.

**Pull request merged**
