### PR TITLE
Ide 3972 23

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
screenshot:
屏幕快照 2019-05-02 下午1 36 01

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
ft retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/4400. [See changes here.](https://github.com/gamerson/liferay-ide/compare/9a42d3e40~6...9a42d3e40) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
