### PR TITLE
IDE-3500 rename

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by yanan** [comment]
Mainly internet problem, jenkins retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/3386. [See changes here.](https://github.com/gamerson/liferay-ide/compare/c698bc07a~1...c698bc07a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
