### PR TITLE
fix message

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by gamerson** [comment]
Merged, thanks! See <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by AndyWu2015** [comment]
hey Greg , I didn't find this is merged . Could you double check ?

**Comment by gamerson** [comment]
Looks like there is a merge conflict, can you rebase and resend?

**Comment by AndyWu2015** [comment]
ok, id doesn't matter , I will squash it onto my later pr

**Pull request closed without merging**
