### PR TITLE
IDE-4867 extract convert cfg to a seprate class

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
ci:retest

**Comment by simonjhy** [comment]
ci:retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/5149. [See changes here.](https://github.com/gamerson/liferay-ide/compare/88fc39ce9~3...88fc39ce9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/simonjhy/liferay-ide/pull/295. [See changes here.](https://github.com/gamerson/liferay-ide/compare/88fc39ce9~3...88fc39ce9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
