### PR TITLE
Sf for kaleo

### PR DESCRIPTION
**Pull request by jtydhr88**
thanks @haoyisun, and please try to add more ui tests for kaleo editor and publish function

### CODE REVIEW

**Comment by yanan** [comment]
jenkins retest

**Comment by haoyisun** [comment]
ok, @jtydhr88  I will do that

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
close to wait ui tests finish and need to rebase on ui tests

**Pull request closed without merging**
