### PR TITLE
new code upgrade ui

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 481c58647693c5c870695581b49ecabab7f6f1f0

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit fcc1fcdbad22fea520b7ab7fb4595e92df7aa882

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 1a2ab3f8c72e5550b949433a390068b66f1e67c0

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 481c58647693c5c870695581b49ecabab7f6f1f0

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit ef1897dfbbdb2c61294b6321a01727e76eb393da

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 720c5dbe73e1186726439d3cacfaa9620965cc69

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit e161f3ae612bc119a517c4ec289405be8d22495f

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit c59c1d777175b1e5a763b7303570c6f892c4de51

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit e4b4e9858c2b0c3853f91196f95cd1914fdee1aa

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit cc40f7a00682aec396def23af9ec4ee39155d138

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 4dd2c977c78019d8423641e9d8cfbeed5487bb43

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit cb564b2c322125a29aacc22a5b72f0535e0f50d2

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 3c1de90359ec50d65e4ab534640c493b4e6edc69

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 625c0eedbfc82fe33ea9316f7757f5cbd87cda1b

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 625c0eedbfc82fe33ea9316f7757f5cbd87cda1b

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit ab95d5bf4db1da0596224089b5ca09693d78cddb

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 8103c46f1279b1671588f35490820222c307f192

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 5ffdc108a928cc505632f212ea639ad113e033e0

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 3b6ba4e38b55980dba2c1c7f96a3a699445a522c

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 95ca9d7cb0b23e28612506d75ce5a76fa1908827

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 00d626beec22aa76ffed83d6ab147850bd9a85e6

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 6a1a298d9cbbb310c32857d1960f8f11a8c01695

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit a693dc8ff005568becca100e7f6d0640059b3399

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 3eabee92e47c6effd591c857d2d7d131bb361318

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 20f1d22257935140d5586de28a1c94573240de4f

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 9d83b5d736c4de4e3a87be47b9780905c9b1b952

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/jtydhr88/liferay-ide/pull/87. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
