### PR TITLE
IDE-2663 Code Upgrade Base UI

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
@gamerson Now I made changes:
1. add the menu button under "Project", you can click it to open our tool editor.
2. In the background I create a hide project ".liferay-ide" and create a file "liferay-code-upgrade.xml" to let tool to open.
3. the editor's outline part will be hide by default, but I don't remove the hide button yet.
4. For now, If you close the editor and reopen it will be at first page (Welcome page).
Thanks.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Hey @jtydhr88 

1) lets remove the "migrate project to liferay 7..." action
2) we need to remove the "source" page for the editor.
3) we don't need to save this in a project.  we can save it in a .metadata/.plugins/com.liferay.ide.project.ui/code-upgrade-tool-tstamp.xml or somethign like that.  We should be able to make the editor support regular "File" instead of IFile

**Comment by gamerson** [comment]
Please resend, thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
