### PR TITLE
IDE-2164 Add support for dynamically get osgi integration point

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by lovettli** [comment]
Hey Greg.
I talk with Simon about How to avoid multiple connections to the Agent . Simply we make ServiceSupervisor combined with BundleSupervisor. BundleSupervisor connect Agent at once then we use this connection to get services information.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/simonjhy/liferay-ide/pull/9. [See changes here.](https://github.com/gamerson/liferay-ide/compare/205f368~3...205f368) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
hey @simonjhy i sent you a new pull along with my review commits to your fork.  Can you test it and then resend if everything is good?  Thanks

**Pull request closed without merging**
