### PR TITLE
IDE-3492 null check

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @jtydhr88  can you take a look?

**Comment by yanan** [comment]
Build Failed.
 No test results found.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 1fc1782f01937282c151415eef4e628ca42e2848 on build 6

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/6/checker.html for detailed testing results

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 1fc1782f01937282c151415eef4e628ca42e2848 on build 6

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/6/checker.html for detailed testing results

**Comment by gamerson** [comment]
hey @jtydhr88 let me know once you know why the tests are failling.

**Comment by jtydhr88** [comment]
I will check it today

**Comment by yanan** [comment]
Build Failed.
 7 tests run, 0 skipped, 7 failed.
SDK test Failed on Jenkins http://ide-build-1:9090/ on this commit 1fc1782f01937282c151415eef4e628ca42e2848 on build 2

**Comment by yanan** [comment]
SDK test Failed on Jenkins http://ide-build-1:9090/ on this commit 1fc1782f01937282c151415eef4e628ca42e2848 on build 2

**Comment by yanan** [comment]
Build Failed.
 9 tests run, 0 skipped, 9 failed.
Hook test Failed on Jenkins http://ide-build-1:9090/ on this commit 1fc1782f01937282c151415eef4e628ca42e2848 on build 3

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/3/checker.html for detailed testing results

**Comment by yanan** [comment]
Hook test Failed on Jenkins http://ide-build-1:9090/ on this commit 1fc1782f01937282c151415eef4e628ca42e2848 on build 3

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/3/checker.html for detailed testing results

**Comment by yanan** [comment]
Build Failed.
 8 tests run, 0 skipped, 8 failed.
Layout Template test Failed on Jenkins http://ide-build-1:9090/ on this commit 1fc1782f01937282c151415eef4e628ca42e2848 on build 3

**Comment by yanan** [comment]
Layout Template test Failed on Jenkins http://ide-build-1:9090/ on this commit 1fc1782f01937282c151415eef4e628ca42e2848 on build 3

**Comment by yanan** [comment]
Build Failed.
 18 tests run, 0 skipped, 18 failed.
Portlet test Failed on Jenkins http://ide-build-1:9090/ on this commit 1fc1782f01937282c151415eef4e628ca42e2848 on build 4

**Comment by yanan** [comment]
Portlet test Failed on Jenkins http://ide-build-1:9090/ on this commit 1fc1782f01937282c151415eef4e628ca42e2848 on build 4

**Comment by yanan** [comment]
Build Failed.
 13 tests run, 1 skipped, 12 failed.
Server test Failed on Jenkins http://ide-build-1:9090/ on this commit 1fc1782f01937282c151415eef4e628ca42e2848 on build 4

**Comment by yanan** [comment]
Server test Failed on Jenkins http://ide-build-1:9090/ on this commit 1fc1782f01937282c151415eef4e628ca42e2848 on build 4

**Comment by yanan** [comment]
Build Failed.
 25 tests run, 2 skipped, 23 failed.
Theme test Failed on Jenkins http://ide-build-1:9090/ on this commit 1fc1782f01937282c151415eef4e628ca42e2848 on build 4

**Comment by yanan** [comment]
Theme test Failed on Jenkins http://ide-build-1:9090/ on this commit 1fc1782f01937282c151415eef4e628ca42e2848 on build 4

**Comment by yanan** [comment]
Build Failed.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 1fc1782f01937282c151415eef4e628ca42e2848 on build 9

**Pull request closed without merging**
