### PR TITLE
IDE-2062Import multiple sdk projects base on sdk location in IDE3.0

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Hey @simonjhy I looked at this feature.

If the workspace already has a WorkspaceSDK project, then that is the one that should be used.  We shouldn't let the user specify anyother one since it will be invalid.  And if the workspace doesn't have a "Workspace SDK" project then they can import with this one.

**Comment by gamerson** [comment]
Also can you remove the old code or the old wizard along with this pull request?  thanks.

**Comment by gamerson** [comment]
closing see comments, please resend.

**Comment by simonjhy** [comment]
Greg, do you mean we need to hide the sdk location and sdk version properties while the workspace has already one sdk?

**Comment by gamerson** [comment]
Don't need to highlight it but disable it as you have already done.

On Wed, Sep 9, 2015 at 2:19 AM, simon.jiang <notifications@github.com>
wrote:

> Greg, do you mean we need to hide the sdk location and sdk version
> properties while the workspace has already one sdk?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamerson/liferay-ide/pull/1118#issuecomment-138810650>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Pull request closed without merging**
