### PR TITLE
IDE-3440 switch to liferay workspace perspective after importing liferay-workspace project

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by AndyWu2015** [comment]
according to http://cloud-10-50-0-162:8081/job/liferay-ide-pr-tester/112/console
the error is not about this pull request.

**Comment by jtydhr88** [comment]
ci:retest

**Comment by jtydhr88** [comment]
ci:retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2710. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
