### PR TITLE
IDE-4705 remove system out print

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by yanan** [comment]
Source format successfully.

**Comment by yanan** [comment]
Integration Tests run successfully.

**Comment by yanan** [comment]
ImportLiferayWorkspaceWizardMavenTests.importLiferayWorkspaceWithDownloadBundle: ft retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
