### PR TITLE
IDE-2967 Improve logic of new gradle/maven module project wizard

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 9112c91801596461bc44f8d74975ec41b3ca6ec1 on build 208

**Comment by gamerson** [comment]
Why did you comment out the tests?  we need to fix them as they are not invalid as far as I know.

**Comment by simonjhy** [comment]
@gamerson, after discussed with terry about the sapphire module project wizard. I found the component and package name has a default value service base on project name. As you know, the component class name and package name fields all were placed in second page. While the validation service return failed result, the first page project name can't get this validation failure result although we have register listener for project name in component class name and package name field. If we  want to absolutely resolve this, we have to remove the default value service and manually call component class and package name refresh method, this solution has a precondition that the project name and component class and package name fields can't have recycle listener for them. 

This solution can make the wizard know the other not displayed page has error and make the wizard finish button show disable status. This is a sapphire bug we discussed it before. While sapphire didn't resolve this, I don't find other good solution about this.

**Comment by jtydhr88** [comment]
@simonjhy @gamerson I don't think we should make this problem too complex, just I said in email, the root of problem is: is there a relationship between "Project Name" and "Component Name/Package Name"? for this one, I don't think so, so I think we can just give some "simple" default name will be ok.

**Pull request closed without merging**
