### PR TITLE
IDE-2419 make gradle.core.tests complie in eclipse

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by AndyWu2015** [comment]
Hey @gamerson  , I update the blade-tools in my dev eclipse , so the com.liferay.blade.gradle.module was uninstalled and the gradle.core.tests didn't compile in eclipse. So I add this build path configuration.

**Comment by gamerson** [comment]
@AndyWu2015 we shouldn't have to do this, it should just work because of it being exported from the other project.  but I don't know what is happening.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged, thanks! See ce55645...1b4bb77 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by AndyWu2015** [comment]
I guess the eclipse can't recognize the export packages if it is from jar inside a plugin configured with Bundle-ClassPath in MANIFEST.MF

**Pull request merged**
