### PR TITLE
IDE-2589 search for java file then add properties

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by yanan** [comment]
Ide build succesfully but there're some errors in ide:

1. java.lang.StringIndexOutOfBoundsException when adding properties to Activator module in error log, can we remove properties in the second page for Activator module?
2. can not finish creating ServiceBuilder module project
3. it takes longer after click Finish button to create a module

**Comment by yanan** [comment]
Hi @AndyWu2015 , can you help take a look when you're available? Thanks.

**Comment by yanan** [comment]
Thanks Andy. 

This new commit fix the errors. 

@gamerson  We now remove adding properties to Activator module, please let us know if we needs to add it back.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged, thanks! See e62830a...0691ee3 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
