### PR TITLE
IDE-4141 add support to import Liferay workspace project

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
it retest

**Comment by jtydhr88** [comment]
@yanan please open the new pr to test the new Integration Tests checker or not use this one.

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by gamerson** [comment]
Merged in a13a0cbd13fb13bbacd92993af9a8edd05e58331. Thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
