### PR TITLE
IDE-2760 update new layouttpl project sdk62 tests

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
jenkins retest

**Pull request closed without merging**
