### PR TITLE
IDE-4268 check null

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by rui123wang** [comment]
it retest

**Comment by lily94299570** [comment]
ft retest

**Comment by lily94299570** [comment]
ft retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/3853. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
