### PR TITLE
IDE-4107 create marker when delete sdk properties at workspace

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by haoyisun** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by yanan** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by haoyisun** [comment]
jenkins retest

**Comment by haoyisun** [comment]
jenkins retest

**Comment by gamerson** [comment]
Merged in a3e257939b54b8cd37b126e26a4ee87b6197f6ca. Thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
