### PR TITLE
IDE-3400 Improve the default name of servers

### PR DESCRIPTION
**Pull request by jtydhr88**
Include ticket 'IDE-3506' and some api fixed.

### CODE REVIEW

**Comment by Camork** [comment]
ci:retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by gamerson** [comment]
Hey @Camork  Please add unit tests for this new fix/feature.  Thanks! cc @jtydhr88

**Comment by Camork** [comment]
OK,got it.

**Pull request closed without merging**
