### PR TITLE
IDE-4553 add upgrade your development environment test for upgrade pl…

### PR DESCRIPTION
**Pull request by yanan**
…anner

### CODE REVIEW

**Comment by lily94299570** [comment]
ft retest

**Comment by yanan** [comment]
ft retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged in 3affee3571e14d6715d466e8ac3268291b2abb4d. Thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
