### PR TITLE
Ide 3590

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
Build Successful.
Test Passed on Jenkins http://ide-build-1:9090/job/Multiple-Job-Test/ on this commit 6986b43b08dac752070c3165af9260e2699e774f on build 19

**Comment by yanan** [comment]
Build Successful.
Test Passed on Jenkins http://ide-build-1:9090/job/Multiple-Job-Test/ on this commit 90702e66082b5ec3f30bb4ac06f90bfe353714dd on build 30
 
Build Successful.

**Comment by yanan** [comment]
Build Successful.

**Comment by yanan** [comment]
Build Failed.
Test Failed on Jenkins http://ide-build-1:9090/job/Multiple-Job-Test/ on this commit 40006fe672275977c46c3e281522b3f4fe5d5d22 on build 31

**Comment by yanan** [comment]
Build Failed.
Test Failed on Jenkins http://ide-build-1:9090/job/Multiple-Job-Test/ on this commit 014227a49189a39d670fdb85626946272dd8b366 on build 34

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by yanan** [comment]
Build Failed.
Test Failed on Jenkins http://ide-build-1:9090/job/Multiple-Job-Test/ on this commit 7e98cdb76c9b935bdfef3b43215eb6b98f7df928 on build 37

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2879. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
