### PR TITLE
Integration tests

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
hey Greg, the new Integration tests folder **integration-tests** is in the root folder, I will add the readme file to say how to run them

**Comment by gamerson** [comment]
but they are not in this pull.  Look at the changed lines in the top right hand corner


+770 −39,745 

The number of added should be about the same as number of deleted.  unless you deleted some unneeded files.

**Comment by jtydhr88** [comment]
I already moved some tests before but I didn't remove the old ones at that time.
The number of - is so big as I remove the the whole project of old gradle.core.tests this time.

**Comment by gamerson** [comment]
Merged in 7729d80836fde587ddf4b1ab7cfd83167315757d <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
