### PR TITLE
IDE-4274 Add breaking change for Spring Extender depencency

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by yanan** [comment]
Integration Tests Build Failed.

Tests Failed on http://ide-build-1:9090/job/Integration-Tests-Checker//1052

**Comment by yanan** [comment]
Integration Tests Build Failed.

Tests Failed on http://ide-build-1:9090/job/Integration-Tests-Checker//1053

**Comment by yanan** [comment]
Integration Tests Build Failed.

Tests Failed on http://ide-build-1:9090/job/Integration-Tests-Checker//1054

**Comment by Seiphon** [comment]
ft reset

**Comment by Seiphon** [comment]
ci:retest

**Comment by yanan** [comment]
Integration Tests run successfully.

**Comment by yanan** [comment]
lost connection: ft retest

**Comment by gamerson** [comment]
Merged in 5fe82994b1b2ef5ad33be6ec8509090133c93e38. Thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
