### PR TITLE
Ui tests

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
Internet problem, will make a mirror of eclipse p2 tomorrow after finish downloading all eclipse mirror.
jenkins retest

**Comment by yanan** [comment]
jenkins retest

**Comment by rui123wang** [comment]
jenkins retest

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
jenkins retest

**Pull request merged**
