### PR TITLE
IDE-3340 Liferay IDE check server status error for Liferay Portal CE …

### PR DESCRIPTION
**Pull request by jtydhr88**
…GA4 for JBoss EAP

### CODE REVIEW

**Comment by yanan** [comment]
Build Failed.
 No test results found.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 8a6478e62740a9e9539f8894913f49e2965bd3db on build 44

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 8a6478e62740a9e9539f8894913f49e2965bd3db on build 44

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by yanan** [comment]
Build Failed.
 No test results found.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 8a6478e62740a9e9539f8894913f49e2965bd3db on build 46

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 8a6478e62740a9e9539f8894913f49e2965bd3db on build 46

**Comment by jtydhr88** [comment]
closed as tests failed

**Pull request closed without merging**
