### PR TITLE
update blade

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
ci:retest

**Comment by yanan** [comment]
jenkins retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/3412. [See changes here.](https://github.com/gamerson/liferay-ide/compare/2c92c177f~1...2c92c177f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
