### PR TITLE
IDE-4726 add new liferay spring mvc portlet test and sf

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @yanan  it seems the integration/functional tests didn't run.  Maybe you can restart them once you return

**Comment by yanan** [comment]
it retest

**Comment by yanan** [comment]
ft retest

**Comment by gamerson** [comment]
hey @yanan  is this ready to be merged?

**Comment by yanan** [comment]
I will rebase to latest master and resend, thanks

**Pull request closed without merging**
