### PR TITLE
IDE-4643 fix null exception for upgrade problem tests

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
internet problem: ft retest

**Comment by yanan** [comment]
internet problem: ft retest

**Comment by yanan** [comment]
internet problem: ft retest

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
ft retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
