### PR TITLE
IDE-4407

### PR DESCRIPTION
**Pull request by Seiphon**
Hi @gamerson 

I made some changes this time, like using Pattern instead of String to store pattern, using getModelForEdit() rather than getModelForRead() and remove the useless loop for problems.

Thanks,
Seiphon

### CODE REVIEW

**Comment by gamerson** [comment]
hey @Seiphon  take a look at the failing tests:


com.liferay.blade.test.InitJSPParseTest.initParseErrorCheck | 49 sec | 1
-- | -- | --
com.liferay.blade.test.apichanges.DescriptorAutoCorrectTest.autoCorrectProblems | 9 ms | 1
com.liferay.blade.test.apichanges.DescriptorsTest.test | 0 ms | 1
com.liferay.blade.test.apichanges.DescriptorsTest.test2 | 0 ms | 1
com.liferay.blade.test.apichanges71.Descriptors71Test.test | 1 ms | 1
com.liferay.blade.test.apichanges71.Descriptors71Test.test2 | 0 ms | 1
com.liferay.ide.maven.core.tests.NewMavenLiferayWorkspaceOpTests.testNewMavenLiferayWorkspaceInitBundle | 3.1 sec | 13
com.liferay.ide.maven.core.tests.NewMavenLiferayWorkspaceOpTests.testNewMavenLiferayWorkspaceSetUrl


http://cloud-10-50-0-162:8081/job/liferay-ide-pr-tester/1581/testReport/

**Comment by Seiphon** [comment]
Hi @gamerson 

The test failed because the filter only contains impleName, but the version is also need when there are two FileMigrator have same impleName.
I added a new commit to fix this issue, please review it when you are free.

Thanks,
Seiphon

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/3796. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
