### PR TITLE
IDE 2150 rebased

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged, thanks! See 93cc34a...9f47263
93cc34a...9f47263 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
@AndyWu2015 Nice work Andy!  Good job getting this finished.

**Comment by AndyWu2015** [comment]
the function setting layout of ProjectExplorer is not stable , I've created a ticker for this :https://issues.liferay.com/browse/IDE-2165

**Pull request merged**
