### PR TITLE
new SF

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @jtydhr88  can you let me know this failed?

**Comment by jtydhr88** [comment]
Hey greg, you can click the https://testing-liferayide.wedeploy.io/record/items.html to see the failure build or tests right now.
For this change, build number 183 the it caused by some unknown typho issue on the jenkins server:
[ERROR] Internal error: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST /var/lib/jenkins/.m2/repository/p2/osgi/bundle/com.liferay.ide.service.ui/3.2.0.201808142257-ga1/com.liferay.ide.service.ui-3.2.0.201808142257-ga1.jar: zip file is empty -> [Help 1]

org.apache.maven.InternalErrorException: Internal error: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST /var/lib/jenkins/.m2/repository/p2/osgi/bundle/com.liferay.ide.service.ui/3.2.0.201808142257-ga1/com.liferay.ide.service.ui-3.2.0.201808142257-ga1.jar: zip file is empty

**Comment by jtydhr88** [comment]
We always can call ft retest to retest

**Comment by jtydhr88** [comment]
ft retest

**Comment by jtydhr88** [comment]
it retest to retest integration test
And ft retest to retest fanctional test

**Comment by jtydhr88** [comment]
it retest

**Comment by jtydhr88** [comment]
I need your help to check out the tycho build error I posted when you are in China, thanks

**Comment by jtydhr88** [comment]
ci:retest

**Comment by jtydhr88** [comment]
ft retest

**Pull request closed without merging**
