### PR TITLE
IDE-4501 Add quick fix for gradle dependencies

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
ft retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/3974. [See changes here.](https://github.com/gamerson/liferay-ide/compare/715cebb02~1...715cebb02) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
