### PR TITLE
IDE-3041 Move WebsphereCore to Liferay IDE from studio

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by yanan** [comment]
Build Failed.
 No test results found.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 46c7b4084cdf5702eed66e6296636f553ba5ec86 on build 1

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 46c7b4084cdf5702eed66e6296636f553ba5ec86 on build 1

**Comment by yanan** [comment]
Can one of the admins verify this patch?

**Comment by yanan** [comment]
Sorry, testing for ui-tests pull request tester on build-1.

**Comment by yanan** [comment]
ok to test

**Comment by yanan** [comment]
Build Failed.
 No test results found.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 46c7b4084cdf5702eed66e6296636f553ba5ec86 on build 7

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 46c7b4084cdf5702eed66e6296636f553ba5ec86 on build 7

**Comment by yanan** [comment]
Build Failed.
 No test results found.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 46c7b4084cdf5702eed66e6296636f553ba5ec86 on build 11

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 46c7b4084cdf5702eed66e6296636f553ba5ec86 on build 11

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
Build Failed.
 No test results found.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 46c7b4084cdf5702eed66e6296636f553ba5ec86 on build 20

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 46c7b4084cdf5702eed66e6296636f553ba5ec86 on build 20

**Comment by jtydhr88** [comment]
@simonjhy close to wait your fixing

**Pull request closed without merging**
