### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by AndyWu2015** [comment]
jenkins retest

**Comment by AndyWu2015** [comment]
jenkins restart

**Comment by AndyWu2015** [comment]
ci:retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2543. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
