### PR TITLE
IDE-3303 update maven archetype version to latest

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by AndyWu2015** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
@gamerson I think we can put this change to next version if it caused the unknown tests fails.

**Comment by gamerson** [comment]
Once we update blade, we need to update the maven archetypes because if not, the 'maven' and 'gradle' wont create the same type of project

**Comment by AndyWu2015** [comment]
sure.

**Comment by gamerson** [comment]
addressed in separate PR

**Pull request closed without merging**
