### PR TITLE
IDE-3559 update sf finished project

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by AndyWu2015** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2619. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
