### PR TITLE
Add json files which include deprecated methods

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:retest

**Comment by Seiphon** [comment]
ci:test

**Comment by yanan** [comment]
ft retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged in ebf4f9c8e9f2f796c320685daa684cddf956c68f. Thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
