### PR TITLE
IDE-3206 check if preference page is still open

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by AndyWu2015** [comment]
It doesn't matter , we don't need this in m3

**Comment by AndyWu2015** [comment]
jenkins retest

**Comment by yanan** [comment]
jenkins retests

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 30a95abc9a8f52fbfac26c3d5a024e9013488029 on build 234

**Comment by AndyWu2015** [comment]
jenkins retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2228. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
