### PR TITLE
IDE-4520 update test dependencies to ce 712 ga3 and dxp 71 sp1

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
it retest

**Comment by yanan** [comment]
ci:retest

**Comment by yanan** [comment]
it retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged in ee4e7d28cfe702f8152e99e2fac704c5b4154619. Thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
