### PR TITLE
IDE-2916 add build-wsdd action

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @AndyWu2015  can you rebase? Thanks.

**Comment by gamerson** [comment]
hey @AndyWu2015  can you rebase this on master?  Thanks

**Comment by AndyWu2015** [comment]
rebased and refreshed this pr

**Comment by AndyWu2015** [comment]
jenkins retest

**Comment by AndyWu2015** [comment]
jenkins retest

**Comment by AndyWu2015** [comment]
jenkins restart

**Pull request closed without merging**
