### PR TITLE
IDE-3560 sf on com.liferay.ide.server.ui

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by JoyeLuo** [comment]
ci:retest

**Comment by JoyeLuo** [comment]
jenkins:retest

**Comment by JoyeLuo** [comment]
ci:retest

**Comment by gamerson** [comment]
Merged in 0da3f5c70bc79cf3e27e898d955211393ac0af71 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
