### PR TITLE
update functional tests on fragment and perspective improvements

### PR DESCRIPTION
**Pull request by yanan**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @yanan  should I go ahead and merge these?

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
Hello @gamerson , please help merge this. 
Failed function tests: LIFERAY_UPGRADE_PLANNER_ACTIONS(Created ticket https://issues.liferay.com/browse/IDE-4773 which we'll fix on 3.8.1)

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/4890. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
