### PR TITLE
blade 3.9.0-SNAPSHOT build

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by yanan** [comment]
Integration Tests run successfully.

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
Hi @gamerson , for funcitonal tests errors:
1. IDE bugs: I've sent an email listing the testing results on this blade 3.9.0.  
2. Other tests need to be updated: I've send pr here  which we've updated
https://github.com/gamerson/liferay-ide/pull/4806

**Comment by gamerson** [comment]
thanks @yanan  for the update.  We are working on a new blade-3.9.0 snapshot that will fix some of these issues.

**Pull request closed without merging**
