### PR TITLE
IDE-2144 Add new OSGI Module Wizard second page

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
screen shot 2016-01-07 at 6 53 16 pm

Choosing service or serviceWrapper there is not a list of services to choose from.  Remember that I said we need to include a static list for 3.0M1.  We can integrate the services command later.

Also even if the user selects some service that we don't know about it should be allowed, don't force the value entered to be among the possible values.

**Comment by gamerson** [comment]
Please resend, thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by simonjhy** [comment]
I have directly define a static serice list in codes. I wil test it in mac, it works well in my local and it can show service list.

**Pull request closed without merging**
