### PR TITLE
add a dialog to show upgrade details

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Hey Terry, can you upload a screenshot of this feature?

**Comment by jtydhr88** [comment]
add an action:
屏幕快照 2019-04-11 下午1 50 54
and then show the details of current plan:
屏幕快照 2019-04-11 下午1 52 16

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/jtydhr88/liferay-ide/pull/994. [See changes here.](https://github.com/gamerson/liferay-ide/compare/9621a933f~7...9621a933f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
