### PR TITLE
IDE-3623 include features that need to be updated in our visible category

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @yanan  and @jtydhr88   here is the solution

in order to let our users know that they need to 'update' the m2e features we need to include them in our category for "liferay ide" on our website.  See here:

https://github.com/gamerson/liferay-ide/pull/2909/commits/379d94be59924b33bcc2c4e175c6501ddb2335f1

Now this results in this and users should be able to see it.  ANd if they click the top level category checkbox it should work as expected.

screen shot 2018-01-12 at 6 30 54 pm

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
ci:retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2925. [See changes here.](https://github.com/gamerson/liferay-ide/compare/ace2165~1...ace2165) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
