### PR TITLE
IDE-2149 Add a new component wizard for an existing Module project

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
hey @simonjhy  a few comments

1. the correct term is DSComponent not OSGiModule, so we need to rename everything to be "DSComponent"
2. we don't need the extension point.  Extension points are useful if there is a separation between what happens for gradle and for maven.  but for DSComponents they are identical, so we don't need all of the extension point stuff, lets remove it and simplfy this quite a bit.

cc @jtydhr88

**Comment by gamerson** [comment]
Please resend, thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by simonjhy** [comment]
you mean we don't support add new module for maven module project in future? Can we remove all wizard core and UI code to gradle core and gradle ui plugin?

**Comment by simonjhy** [comment]
The target  extension point I added is that I think we need to support maven moudle project in future.

**Pull request closed without merging**
