### PR TITLE
Functioanl Tests: maximize eclipse to get a full screen screenshot

### PR DESCRIPTION
**Pull request by yanan**

### CODE REVIEW

**Comment by yanan** [comment]
Source format successfully.

**Comment by yanan** [comment]
Integration Tests run successfully.

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
internet problem: ft retest

**Comment by gamerson** [comment]
Merged in 37996112d691bb19ed2d979cf4634b12c6ecb47c. Thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
