### PR TITLE
IDE-2850 add build wsdd support for gradle projects

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
sf retest

**Comment by yanan** [comment]
integration failure is because of the internet: it retest

**Comment by yanan** [comment]
SB_DEPLOY_TOMCAT71: ft retest

**Comment by yanan** [comment]
MODULES_EXT__CREATE_TOMCAT71: ft retest

**Comment by yanan** [comment]
internet problem: ft retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/4693. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
