### PR TITLE
Ide 1798

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
Hi Greg,
There is a option "Use code formatter" for js templates and it been selected by default in eclipse.
If we used it, it would break our code fomatter.

**Comment by gamerson** [comment]
that is ok, if they don't have it selected then they will get our format.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/jtydhr88/liferay-ide/pull/1. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
