### PR TITLE
IDE-3722 CodeUpgrade performance improvement for finding breaking cha…

### PR DESCRIPTION
**Pull request by jtydhr88**
…nges

### CODE REVIEW

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/3133. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
