### PR TITLE
UI test case about kaleo

### PR DESCRIPTION
**Pull request by haoyisun**
UI test case about kaleo

### CODE REVIEW

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
ok to test

**Comment by yanan** [comment]
ci:retest

**Comment by yanan** [comment]
Build Failed.
 214 tests run, 14 skipped, 1 failed.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit e047822cb89d39afc743f59c4d8039491be95c8c on build 36

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit e047822cb89d39afc743f59c4d8039491be95c8c on build 36

**Comment by gamerson** [comment]
hey @yanan  there is one failed test.  I will need to hear from you if this is good to merge since I can't check it.

**Pull request closed without merging**
