### PR TITLE
IDE-2307 remove org.eclipse.ui.preferenceTransfer extension point

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged, thanks! See 80c7dd2...f909aa7
80c7dd2...f909aa7 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
@AndyWu2015 will this not disable the preference copying when launching a new workspace?

**Comment by AndyWu2015** [comment]
no , this will not disable the preference copying.

**Pull request merged**
