### PR TITLE
Ide 4701 update bundle url and target platform from 7.2.0 to latest 7.2.1

### PR DESCRIPTION
**Pull request by yanan**
These are the changes on IDE side, already sent another pr to your liferay-portal repo here: gamerson/liferay-portal#367

### CODE REVIEW

**Comment by yanan** [comment]
Source format successfully.

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Functional-Tests-Checker//1094

**Comment by yanan** [comment]
Integration Tests run successfully.

**Comment by yanan** [comment]
failed because of downloading sources: ft retest

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Functional-Tests-Checker//1095

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
Functional tests passed on CN Linux server on 6a11a9ef4c06daaa64203feec73ac26f28c68514

http://ide-build-1:9090/job/Functional-Tests-Checker//1096

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
