### PR TITLE
More maven service builder fixes

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 5fd32e06105150a5b57460d4bac27b13bed980f4 on build 139

**Comment by gamerson** [comment]
jenkins retest

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 5fd32e06105150a5b57460d4bac27b13bed980f4 on build 140

**Comment by gamerson** [comment]
jenkins retest

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit bcecb55194251e9f72ef2b500fa8c79feee09ba0 on build 141

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit bcecb55194251e9f72ef2b500fa8c79feee09ba0 on build 142

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 0bbeabaa3735b59ad0a53462ac7ddb0bc3871de6 on build 143

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 59aa6146bb9ee27c17f1fa6081ff2f7d38ceb493 on build 144

**Pull request merged**
