### PR TITLE
IDE-3500 add watch support

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
ci: retest

**Comment by jtydhr88** [comment]
ci: retest

**Comment by jtydhr88** [comment]
ci:retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by gamerson** [comment]
Also Terry can you rebase and resend? thanks

**Pull request closed without merging**
