### PR TITLE
ui tests for add console content checker

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @yanan  what is the status for these tests?

**Comment by gamerson** [comment]
Oh i see the tests are still running :)

**Comment by gamerson** [comment]
really nice work @jtydhr88  @yanan  @lily94299570 i see we've added new tests and they are showing up here:

```
Build Successful.
210 tests run, 14 skipped, 0 failed.
Test Passed on Jenkins http://ide-build-1:9090/ on this commit f13a984 on build 40
```

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2781. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2782. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by yanan** [comment]
Build Successful.
 218 tests run, 14 skipped, 0 failed.
Test Passed on Jenkins http://ide-build-1:9090/ on this commit 7bf63d9dc5e70bcd8a5e7ce547fae72cc14e0c89 on build 41

**Comment by yanan** [comment]
Test Passed on Jenkins http://ide-build-1:9090/ on this commit 7bf63d9dc5e70bcd8a5e7ce547fae72cc14e0c89 on build 41

**Pull request closed without merging**
