### PR TITLE
add overlay icon

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by gamerson** [comment]
@simonjhy  Nice work! thanks for update.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged in 7796be654c380b462d71ecaaf74736cc836cebe8. Thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Hey @simonjhy  Recently Chris added a "FAILED" status to actions.  Can you send in support for a "red x" overlap image if an Action has Failed status?  Thanks

**Comment by simonjhy** [comment]
ok, do it now.

**Pull request closed without merging**
