### PR TITLE
IDE-2354 Improve columns space in migration view on Windows

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
Build Failed.
Test Failed on Jenkins http://ide-build-1:9090/job/Multiple-Job-Test/ on this commit be4382ecc0735516a48185301cfdd000a0b025d9 on build 25

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
Build Failed.
Test Failed on Jenkins http://ide-build-1:9090/job/Multiple-Job-Test/ on this commit be4382ecc0735516a48185301cfdd000a0b025d9 on build 33

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2876. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
