### PR TITLE
IDE-3214 support mutiple modules folder and fix bug

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by AndyWu2015** [comment]
jenkins retest

**Comment by AndyWu2015** [comment]
jenkins retest

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 7c0326926b5e02687240e8c3b3466da2fe6bb339 on build 233

**Comment by AndyWu2015** [comment]
jenkins retest

**Comment by gamerson** [comment]
hey @AndyWu2015  can you add some unit tests for this change and resend?  Thanks!

**Comment by AndyWu2015** [comment]
ok got it

**Pull request closed without merging**
