### PR TITLE
IDE-4473 fix liferay watch decorator issue

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
ci:retest

**Comment by yanan** [comment]
it retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/3918. [See changes here.](https://github.com/gamerson/liferay-ide/compare/822a76101~3...822a76101) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
