### PR TITLE
IDE-4448 Using the highest version when there are two services have s…

### PR DESCRIPTION
**Pull request by jtydhr88**
…ame implName

### CODE REVIEW

**Comment by jtydhr88** [comment]
ci:retest

**Comment by jtydhr88** [comment]
ci:retest

**Comment by Seiphon** [comment]
ci:retest

**Comment by Seiphon** [comment]
ci:retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/3849. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
