### PR TITLE
Ui tests

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by jtydhr88** [comment]
jenkins retest

**Comment by gamerson** [comment]
Merged in 5ea08fb74cf683a50e104f292b3ce87d96b8f625 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
