### PR TITLE
IDE-3497 update portal resources to latest Dxp sp6, ce ga5 and 1.0.16…

### PR DESCRIPTION
**Pull request by yanan**
… sdk

### CODE REVIEW

**Comment by yanan** [comment]
Build Failed.
 190 tests run, 9 skipped, 35 failed.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 579fb6c019256f5c615e6479cd2dfcaa6b17177e on build 10

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 579fb6c019256f5c615e6479cd2dfcaa6b17177e on build 10

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 579fb6c019256f5c615e6479cd2dfcaa6b17177e on build 15

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
Build Failed.
 210 tests run, 13 skipped, 20 failed.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 579fb6c019256f5c615e6479cd2dfcaa6b17177e on build 16

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 579fb6c019256f5c615e6479cd2dfcaa6b17177e on build 16

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
ci:retest

**Comment by yanan** [comment]
Hello @gamerson ,

To pass these tests, we need to upload portal-tomcat-ga5 zip file to /home/jenkins/resources folder in LAX testing machine.

Can you please help upload liferay-ce-portal-tomcat-7.0-ga5-20171018150113838.zip? Thanks.

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2760. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
