### PR TITLE
IDE-4645 add dependency as well when fixing import issues on gradle p…

### PR DESCRIPTION
**Pull request by jtydhr88**
…rojects

### CODE REVIEW

**Comment by jtydhr88** [comment]
ft retest

**Comment by jtydhr88** [comment]
ft retest

**Comment by jtydhr88** [comment]
ft retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged in bdf17bcd637d422afefaa6ff750a5ad729eec543. Thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
