### PR TITLE
IDE-2946 update NewFragmentFilesWizardGradleTests.java

### PR DESCRIPTION
**Pull request by jtydhr88**
Good Job! Thanks @rui123wang

### CODE REVIEW

**Comment by yanan** [comment]
Build Failed.
 189 tests run, 9 skipped, 37 failed.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 34cc8755247655d4f7b0dbaba225c81c16e243dd on build 12

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 34cc8755247655d4f7b0dbaba225c81c16e243dd on build 12

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2753. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
