### PR TITLE
IDE-3398 add quick link "Import New Liferay Workspace From Installer" in intro page

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by AndyWu2015** [comment]
jenkins retest

**Comment by AndyWu2015** [comment]
jenkins retest

**Comment by AndyWu2015** [comment]
jenkins retest

**Comment by gamerson** [comment]
Merged, thanks! See 93fa918...9c56887 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
