### PR TITLE
update blade regularly

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
Java runtime error: it retest

**Comment by yanan** [comment]
it retest

**Comment by yanan** [comment]
ft retest

**Comment by gamerson** [comment]
What is the status of these tests?

**Comment by jtydhr88** [comment]
the testing servers in China office got error, Ashley is fixing them.

**Comment by yanan** [comment]
it retest

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
ft retest

**Comment by jtydhr88** [comment]
ft retest

**Comment by yanan** [comment]
delete maven war test failed on windows: ft retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/3817. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
