### PR TITLE
update com.liferay.gradle.plugins.workspace version to 1.5.0

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by AndyWu2015** [comment]
Hey @gamerson  , I see such error many times , is there any issue with our LAX jenkins server , it was downloading about 120MB objects .Don't know why this behavior shows up.

**Comment by gamerson** [comment]
jenkins retest

**Comment by gamerson** [comment]
hey @AndyWu2015  can you add a ticket for this so we can track it back to a jira ticket?  Thanks

**Comment by AndyWu2015** [comment]
ok

**Pull request closed without merging**
