### PR TITLE
Add docker support for IDE

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
1) I moved add docker server and runtime UI to gradle UI and keep core docker sever and runtime class in sever core. I keep them in sever core, so like startContainer and stopContainer I use docker-java api and these docker core class will be used by gradle or maven in future. If we also need to move them to gradle core, I think we can move them after your dev con presentation.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by simonjhy** [comment]
HI greg, one bug about gogoshelp popup menu and I appended a commit.

**Comment by yanan** [comment]
it retest

**Comment by yanan** [comment]
it retest

**Comment by yanan** [comment]
Integration Tests Build Failed.

Tests Failed on http://ide-build-1:9090/job/Integration-Tests-Checker//992

**Comment by yanan** [comment]
Source format successfully.

**Comment by yanan** [comment]
Source format successfully.

**Comment by yanan** [comment]
Integration Tests Build Failed.

Tests Failed on http://ide-build-1:9090/job/Integration-Tests-Checker//994

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Functional-Tests-Checker//1099

**Pull request closed without merging**
