### PR TITLE
IDE-4646 fix null exception for LiferayConsoleProvider

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
ci:retest

**Comment by yanan** [comment]
internet problem: ft retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/4643. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
