### PR TITLE
Ui tests2

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
Build Failed.
 199 tests run, 11 skipped, 18 failed.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 1a9a8fe28dff5e09755b4f118e2154fb2532c200 on build 17

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 1a9a8fe28dff5e09755b4f118e2154fb2532c200 on build 17

**Comment by gamerson** [comment]
hey @jtydhr88 @yanan 

Since there are failed tests, I wasn't going to merge yet.  Unless you guys say we need to.

Also, Ashley, I'd like to run the UI tests on my system, how can I do that?

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2751. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by yanan** [comment]
Hello @gamerson ,

After restructure by Terry, steps are as following to run UI tests on Mac:
1. go to "liferay-ide/ui-test"' folder
2. run 'mvn clean verify -Pui-repo'
3. copy bundle resources to "liferay-ide/tests-resources" folder
- liferay-portal-tomcat-6.2-ce-ga6-20160112152609836
- liferay-plugins-sdk-6.2-ce-ga6-20160112152609836
- liferay-ce-portal-tomcat-7.0-ga4-20170613175008905
- com.liferay.portal.plugins.sdk-1.0.16-withdependencies
4. run ’mvn clean verify -Pui-tests-mac‘

If no step 3, then copy files in “liferay-ide/tests-resources” to your liferay.bundles.dir folder, otherwise, validation tests would fail. And then run the following command instead Step 3 and Step 4:

mvn clean verify -Pui-tests-mac -Dliferay.bundles.dir="${your-resources-folder}"

**Comment by jtydhr88** [comment]
hey @gamerson 
there is a more simply way to run ui test locally,
1, make sure all of files we need already in tests-resources folder
2, go into the folder /ui-tests/script/
3. run the shell or bat on your os

**Pull request closed without merging**
