### PR TITLE
IDE-3578 Only run find breaking change for selected project.

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
Build Failed.
Test Failed on Jenkins http://ide-build-1:9090/job/Multiple-Job-Test/ on this commit 0de0b83ba45fb26279b1106f0078569d5a7d78ed on build 26

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
Build Failed.
Test Failed on Jenkins http://ide-build-1:9090/job/Multiple-Job-Test/ on this commit 0de0b83ba45fb26279b1106f0078569d5a7d78ed on build 28

**Comment by yanan** [comment]
jenkins retest

**Comment by yanan** [comment]
Build Successful.
Test Passed on Jenkins http://ide-build-1:9090/job/Multiple-Job-Test/ on this commit 0de0b83ba45fb26279b1106f0078569d5a7d78ed on build 32
 
Build Successful.

**Comment by yanan** [comment]
Build Successful.

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-ide/pull/2875. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
