### PR TITLE
IDE-2958 put theme outside liferay-workspace because it is not supported

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 73fabf4f4ff02f553af849aae6004ffee4b2e928 on build 138

**Comment by gamerson** [comment]
Hey @AndyWu2015 can you make it so that themes get added to the 'wars' folder?  since they are treated as normal wars.  Also we should make it so that developers can customize the location of modules so they are free to put them anywhere even when there is a workspace project.

**Comment by AndyWu2015** [comment]
yeah, I can add theme to wars  , but the theme project template is wrong , because it does't have 

```
dependencies {
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.theme.builder", version: "2.0.0"
	}
```

in build.gradle. and gradle will complain `Plugin with id 'com.liferay.portal.tools.theme.builder' not found.`

**Comment by AndyWu2015** [comment]
should I add theme to wars now , or until we fix that bug and embed it into blade.jar ?

**Comment by gamerson** [comment]
Lets add to wars now.  I've sent your changes to upstream blade template fixes.

**Comment by AndyWu2015** [comment]
ok got it.

**Pull request closed without merging**
