### PR TITLE
add docker support for IDE

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by yanan** [comment]
Source format successfully.

**Comment by yanan** [comment]
Source format successfully.

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Functional-Tests-Checker//1101

**Comment by yanan** [comment]
Integration Tests Build Failed.

Tests Failed on http://ide-build-1:9090/job/Integration-Tests-Checker//996

**Comment by yanan** [comment]
Hi @simonjhy , I've send a new pr to you here https://github.com/simonjhy/liferay-ide/pull/155 to fix the integration tests.

**Testing results and steps:**
1. create a new liferay gradle workspace
2. set to  use mavenLocal() and update gradle.plugins.workspace version accordingly
3. right click on workspace project and run Liferay > "Init Portal Docker Bundle"
4. start/Debug start the bundle in Servers view
5. deployment successfully on a mvc-portlet and war-mvc-portlet projects, if adding a breakpoint it can stop as expected.
init-docker-bundle
start-in-debug-mode

**Questions:**
1. when go to Window > Preferences > Server > Runtime Environment, Remove the docker server runtime, we will run into the following error in error log:
> Failed to delete server and runtime
> javax.ws.rs.ProcessingException: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;
> com.liferay.ide.gradle.action.InitDockerBundleTaskAction._deleteWorkspaceDockerServerAndRuntime(InitDockerBundleTaskAction.java:191) com.liferay.ide.gradle.action.InitDockerBundleTaskAction.beforeAction(InitDockerBundleTaskAction.java:69)
> com.liferay.ide.gradle.action.GradleTaskAction.run(GradleTaskAction.java:67)

2. About blade 3.8.1
when we create an mvc-portlet module project in gralde workspace project with target platform enabled, the dependency "com.liferay.css.builder" still have version set. Is this expected?
css-builder-version

**Comment by simonjhy** [comment]
ci:test

**Comment by simonjhy** [comment]
ci:test

**Comment by simonjhy** [comment]
ci:retest

**Comment by yanan** [comment]
Source format successfully.

**Pull request closed without merging**
