### PR TITLE
IDE-3601 improve get compile unit cache logic of Code Upgrade

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by yanan** [comment]
Build Failed.
 No test results found.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 2b80bfc0b68d615c05e6cecb1f6037b63db3ce37 on build 27

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/27/checker.html for detailed testing results

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 2b80bfc0b68d615c05e6cecb1f6037b63db3ce37 on build 27

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/27/checker.html for detailed testing results

**Comment by yanan** [comment]
Build Failed.
 No test results found.
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 2b80bfc0b68d615c05e6cecb1f6037b63db3ce37 on build 1

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/1/checker.html for detailed testing results

**Comment by yanan** [comment]
Test Failed on Jenkins http://ide-build-1:9090/ on this commit 2b80bfc0b68d615c05e6cecb1f6037b63db3ce37 on build 1

Refer to https://testing-liferayide.wedeploy.io/ui-testing-reports/1/checker.html for detailed testing results

**Comment by yanan** [comment]
Build Failed.
 13 tests run, 1 skipped, 12 failed.
Server test Failed on Jenkins http://ide-build-1:9090/ on this commit 2b80bfc0b68d615c05e6cecb1f6037b63db3ce37 on build 1

**Comment by yanan** [comment]
Server test Failed on Jenkins http://ide-build-1:9090/ on this commit 2b80bfc0b68d615c05e6cecb1f6037b63db3ce37 on build 1

**Comment by yanan** [comment]
Build Failed.
 25 tests run, 2 skipped, 23 failed.
Theme test Failed on Jenkins http://ide-build-1:9090/ on this commit 2b80bfc0b68d615c05e6cecb1f6037b63db3ce37 on build 1

**Comment by yanan** [comment]
Theme test Failed on Jenkins http://ide-build-1:9090/ on this commit 2b80bfc0b68d615c05e6cecb1f6037b63db3ce37 on build 1

**Comment by gamerson** [comment]
good catch @simonjhy  !

**Pull request merged**
